import {writeFile} from "node:fs/promises";
import {connect,expect} from "./cdp.mjs";

process.on("uncaughtException",error=>{console.error(error);process.exit(1);});

const browser=await connect();const{command,evaluate,wait,exceptions,consoleErrors}=browser;
const clear=await command("Page.addScriptToEvaluateOnNewDocument",{source:"localStorage.clear();"});
await command("Page.reload",{ignoreCache:true});await wait(1000);await command("Page.removeScriptToEvaluateOnNewDocument",{identifier:clear.identifier});

const initial=await evaluate(`({
  title:document.title,
  cash:document.querySelector('#cashValue').textContent,
  nav:document.querySelectorAll('#mainNav [data-nav]').length,
  canvas:Boolean(document.querySelector('#world')),
  touchPad:Boolean(document.querySelector('#touchPad')),
  exposed:Boolean(window.__FRUITOPIA__),
  trees:window.__FRUITOPIA__?.core.state.trees.length,
  counts:window.__FRUITOPIA__?{fruits:__FRUITOPIA__.Config.FRUITS.length,recipes:__FRUITOPIA__.Config.RECIPES.length,buildings:__FRUITOPIA__.Config.BUILDINGS.length,routes:__FRUITOPIA__.Config.ROUTES.length,workers:__FRUITOPIA__.Config.WORKERS.length,minigames:__FRUITOPIA__.Config.MINIGAMES.length,sewerEntrances:__FRUITOPIA__.Config.SEWER_ENTRANCES.length,sewerRecipes:__FRUITOPIA__.Config.SEWER_RECIPES.length,outsideRegions:__FRUITOPIA__.Config.OUTSIDE_REGIONS.length,outsidePlots:__FRUITOPIA__.Config.OUTSIDE_PLOTS.length,upgradeCategories:__FRUITOPIA__.Config.UPGRADE_CATEGORIES.length,phoneApps:__FRUITOPIA__.Config.PHONE_APPS_EXPANDED.length}:{},
  saveVersion:window.__FRUITOPIA__?.core.state.version,
  futureMafiaPlayable:window.__FRUITOPIA__?.Config.FUTURE_MAFIA_GAME.playable
})`);
expect(initial.title==="Fruitopia Tycoon","Wrong title");expect(initial.cash==="$1","New game must start with $1");expect(initial.nav===12,"Twelve main navigation buttons required");expect(initial.canvas&&initial.touchPad&&initial.exposed,"Game shell missing");expect(initial.trees===6,"Six trees required");expect(JSON.stringify(initial.counts)===JSON.stringify({fruits:28,recipes:21,buildings:106,routes:18,workers:14,minigames:27,sewerEntrances:5,sewerRecipes:8,outsideRegions:40,outsidePlots:88,upgradeCategories:16,phoneApps:27}),"Catalog count mismatch");expect(initial.saveVersion===15,"Save version must be 15");expect(initial.futureMafiaPlayable===true,"Mystery Crate configuration must be playable");
expect(await evaluate("document.querySelector('link[rel=manifest]')?.getAttribute('href')==='manifest.webmanifest' && document.querySelector('#connectionStatus')?.textContent.includes('Online')"),"Installable app shell or connection status is missing");
let serviceWorkerReady=false;for(let attempt=0;attempt<30&&!serviceWorkerReady;attempt++){await wait(100);serviceWorkerReady=await evaluate("navigator.serviceWorker.getRegistration().then(Boolean)");}expect(serviceWorkerReady,"Offline service worker did not register");

await evaluate("document.querySelector('#mainNav [data-nav=upgrades]').click();true");await wait(120);
expect(await evaluate("document.querySelector('#dialogTitle').textContent==='Master Upgrade Center' && document.querySelectorAll('.upgrade-sidebar [data-do=upgrade-category]').length===16"),"Master Upgrade Center or its categories did not render");
const upgradeCounts=await evaluate(`(()=>{const catalog=__FRUITOPIA__.core.upgradeCatalog(),count=id=>catalog.filter(item=>item.groups.includes(id)).length;return{total:catalog.length,districts:count('districts'),buildings:count('company-buildings'),office:count('office'),vehicles:count('vehicles'),labs:count('fruit-laboratories'),sewer:count('sewer'),mountain:count('mountain'),seasonal:count('seasonal-bonuses'),unique:new Set(catalog.map(item=>item.key)).size};})()`);
expect(JSON.stringify(upgradeCounts)===JSON.stringify({total:517,districts:64,buildings:106,office:44,vehicles:12,labs:10,sewer:44,mountain:43,seasonal:9,unique:517}),"Upgrade Center does not use every canonical upgrade record");
await evaluate("document.querySelector('[data-do=upgrade-category][data-value=districts]').click();true");await wait(80);
expect(await evaluate("document.querySelector('.upgrade-heading h2').textContent.includes('64 matching') && document.querySelectorAll('.district-upgrade-summary button').length===8 && document.querySelector('.district-upgrade-summary').textContent.includes('Completion reward') && document.querySelectorAll('[data-upgrade-card]').length===24"),"District upgrades, previews, completion rewards, or pagination are incomplete");
const upgradeScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-upgrade-center.png",Buffer.from(upgradeScreenshot.data,"base64"));
await evaluate("document.querySelector('#upgradeSearch').value='Copper Watering Cans';document.querySelector('#upgradeSearch').dispatchEvent(new Event('change',{bubbles:true}));true");await wait(80);
expect(await evaluate("document.querySelectorAll('[data-upgrade-card]').length===1 && document.querySelector('[data-upgrade-card] h3').textContent==='Copper Watering Cans'"),"Upgrade search failed");
await evaluate("document.querySelector('[data-do=upgrade-pin]').click();true");await wait(70);
expect(await evaluate("__FRUITOPIA__.core.state.upgradeCenter.pinned.includes('district:apple-grove-orchard:0')"),"Upgrade pinning failed");
await evaluate("document.querySelector('#upgradeSearch').value='';document.querySelector('#upgradeSearch').dispatchEvent(new Event('change',{bubbles:true}));true");await wait(50);await evaluate("document.querySelector('#upgradeRegion').value='Apple Grove Orchard';document.querySelector('#upgradeRegion').dispatchEvent(new Event('change',{bubbles:true}));true");await wait(60);expect(await evaluate("document.querySelector('.upgrade-heading h2').textContent.includes('8 matching')"),"Upgrade region filter failed");
await evaluate("document.querySelector('[data-upgrade-filter=locked]').click();true");await wait(60);expect(await evaluate("document.querySelector('.upgrade-heading h2').textContent.includes('7 matching') && document.querySelectorAll('.upgrade-card.locked').length===7"),"Upgrade locked-state filter failed");
await evaluate("document.querySelector('#upgradeSort').value='cost';document.querySelector('#upgradeSort').dispatchEvent(new Event('change',{bubbles:true}));true");await wait(50);expect(await evaluate("__FRUITOPIA__.core.state.upgradeCenter.sort==='cost'"),"Upgrade sorting failed");
await evaluate("__FRUITOPIA__.core.state.upgradeCenter.search='';__FRUITOPIA__.core.state.upgradeCenter.region='all';__FRUITOPIA__.core.state.upgradeCenter.filters={affordable:false,available:false,locked:false,purchased:false};__FRUITOPIA__.openPage('upgrades','office');true");await wait(80);
expect(await evaluate("document.querySelector('.upgrade-heading h2').textContent.includes('44 matching') && document.querySelectorAll('.office-evolution span').length===5 && [...document.querySelectorAll('.upgrade-card.locked')].every(card=>card.querySelector('.requirement-list li')&&!card.textContent.includes('Locked.'))"),"Office tree or exact requirement explanations are incomplete");
await evaluate("document.querySelectorAll('[data-do=upgrade-compare]')[0].click();true");await wait(50);await evaluate("document.querySelectorAll('[data-do=upgrade-compare]')[1].click();true");await wait(70);
expect(await evaluate("document.querySelectorAll('.upgrade-comparison>div').length===2"),"Upgrade comparison failed");
await evaluate("document.querySelector('[data-nav=upgrade-detail]').click();true");await wait(60);
expect(await evaluate("Boolean(document.querySelector('.upgrade-detail-dialog')) && document.querySelector('#dialog').textContent.includes('Current effect') && document.querySelector('#dialog').textContent.includes('Next-level effect')"),"Upgrade preview is incomplete");
await evaluate("window.__FRUITOPIA__.openPage('upgrade-detail','building:roadside-fruit-stand');true");await wait(40);
await evaluate("document.querySelector('[data-do=upgrade-map]').click();true");await wait(60);expect(await evaluate("document.querySelector('#dialogLayer').classList.contains('hidden')"),"View on Map did not close the Upgrade Center");

await evaluate("window.__FRUITOPIA__.openPage('map','overview');true");await wait(100);
expect(await evaluate("document.querySelectorAll('.country-node').length===40 && document.querySelectorAll('.map-route').length>=40"),"Illustrated 7,200 × 5,000 outside country map is incomplete");
expect(await evaluate("window.__FRUITOPIA__.world.canMoveTo(57,278) && !window.__FRUITOPIA__.world.canMoveTo(__FRUITOPIA__.Config.OUTSIDE_REGION_BY_ID['cosmic-summit'].x,__FRUITOPIA__.Config.OUTSIDE_REGION_BY_ID['cosmic-summit'].y)"),"Outside-world boundaries did not keep locked mountain land inaccessible");
const mapScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-country-map.png",Buffer.from(mapScreenshot.data,"base64"));
await evaluate("window.__FRUITOPIA__.openPage('outside-region','mountain-base-camp');true");await wait(80);expect(await evaluate("document.querySelector('#dialogTitle').textContent==='Mountain Base Camp' && document.querySelector('#dialog').textContent.includes('Reach Empire level 12') && document.querySelectorAll('.land-steps button').length===4"),"Mountain Base Camp did not expose its exact lock reason and preparation sequence");
await evaluate("window.__FRUITOPIA__.openPage('outside-region','starter-valley');true");await wait(80);expect(await evaluate("document.querySelectorAll('[data-nav=outside-plot]').length===6"),"Starter Valley must expose six fixed building plots");await evaluate("document.querySelector('[data-action=close-dialog]').click();true");

await evaluate("window.__FRUITOPIA__.openPage('map','layers');true");await wait(80);expect(await evaluate("document.querySelectorAll('.map-layer-card').length===10 && document.querySelectorAll('[data-do=outside-teleport]').length===11"),"World-map layers or progression fast-travel hubs are incomplete");
await evaluate("window.__FRUITOPIA__.openPage('shipping','harbor');true");await wait(80);expect(await evaluate("document.querySelector('#dialogTitle').textContent==='Fruitopia Shipping' && document.querySelectorAll('.upgrade-chain span').length===15 && document.querySelector('.shipping-hero')"),"Shipping Harbor screen or its fifteen-stage chain is incomplete");
const shippingScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-shipping-harbor.png",Buffer.from(shippingScreenshot.data,"base64"));
await evaluate("window.__FRUITOPIA__.openPage('shipping','fleet');true");await wait(60);expect(await evaluate("document.querySelectorAll('[data-do=ship-purchase]').length===8"),"All eight ocean vessels are not visible");
await evaluate("window.__FRUITOPIA__.openPage('shipping','contracts');true");await wait(60);expect(await evaluate("document.querySelectorAll('.shipping-contract').length===7 && document.querySelector('#dialog').textContent.includes('Real inventory is committed atomically')"),"Shipping contracts do not explain real cargo preparation");
await evaluate("window.__FRUITOPIA__.openPage('orchard-estate','sections');true");await wait(80);expect(await evaluate("document.querySelectorAll('.orchard-section').length===15 && document.querySelector('.orchard-stage').textContent.includes('Tiny Orchard')"),"Orchard Estate sections or visual stage are incomplete");
const orchardScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-orchard-estate.png",Buffer.from(orchardScreenshot.data,"base64"));
await evaluate("window.__FRUITOPIA__.openPage('orchard-estate','branches');true");await wait(80);expect(await evaluate("document.querySelectorAll('.orchard-branch').length===10 && document.querySelectorAll('.orchard-branch .upgrade-chain button').length===114"),"Orchard Estate deep upgrade branches are incomplete");await evaluate("document.querySelector('[data-action=close-dialog]').click();true");

await evaluate(`(()=>{const g=window.__FRUITOPIA__,pad=g.core.purchasePadById('pad:district:sunny-side-fruit-stand:0','surface');g.core.state.settings.purchaseCountdown='long';g.core.state.player.x=pad.x-5;g.core.state.player.y=pad.y;g.world.findPlayer();g.world.refreshPurchasePads();return true;})()`);
let padApproachReady=false;for(let attempt=0;attempt<30&&!padApproachReady;attempt++){await wait(100);padApproachReady=await evaluate(`(()=>{const g=window.__FRUITOPIA__,pad=g.core.purchasePadById('pad:district:sunny-side-fruit-stand:0','surface'),panel=document.querySelector('#purchasePadPanel');return Boolean(pad)&&g.world.entities.some(item=>item.type==='purchase-pad'&&item.id===pad.id)&&g.world.activePurchasePad?.id===pad.id&&!panel.classList.contains('hidden')&&panel.classList.contains('pad-too-expensive')&&panel.textContent.includes(pad.name)&&panel.textContent.includes('NEED $9 MORE')&&panel.textContent.includes('Builds / changes')&&panel.textContent.includes('Preview');})()`);}expect(padApproachReady,"Approaching a physical pad did not show its canonical price, effect, preview, or unaffordable state");
await evaluate(`(()=>{const g=window.__FRUITOPIA__,pad=g.core.purchasePadById('pad:district:sunny-side-fruit-stand:0','surface');g.core.state.cash=25;g.world.refreshPurchasePads();g.core.state.player.x=pad.x;g.core.state.player.y=pad.y;return true;})()`);
let padCountdownStarted=false;for(let attempt=0;attempt<30&&!padCountdownStarted;attempt++){await wait(100);padCountdownStarted=await evaluate("__FRUITOPIA__.world.purchaseProgress?.id==='pad:district:sunny-side-fruit-stand:0'");}expect(padCountdownStarted,"Walking onto an affordable pad did not begin its cancelable countdown");
await evaluate(`(()=>{const g=window.__FRUITOPIA__;g.core.state.player.x=96;g.core.state.player.y=252;return true;})()`);await wait(180);
let padCanceled=false;for(let attempt=0;attempt<30&&!padCanceled;attempt++){await wait(100);padCanceled=await evaluate(`(()=>{const g=window.__FRUITOPIA__;return !g.world.purchaseProgress&&!g.core.state.districts['sunny-side-fruit-stand'].upgrades.includes(0)&&g.core.state.cash===25&&g.core.state.purchasePads.transactions.length===0&&!document.querySelector('#purchasePadPanel').textContent.includes('Purchasing…');})()`);}expect(padCanceled,"Walking away did not cancel the pad countdown safely");
await evaluate(`(()=>{const g=window.__FRUITOPIA__,pad=g.core.purchasePadById('pad:district:sunny-side-fruit-stand:0','surface');g.core.state.settings.purchaseCountdown='normal';g.core.state.player.x=pad.x;g.core.state.player.y=pad.y;return true;})()`);
let padPurchased=false;for(let attempt=0;attempt<30&&!padPurchased;attempt++){await wait(100);padPurchased=await evaluate("__FRUITOPIA__.core.state.districts['sunny-side-fruit-stand'].upgrades.includes(0)");}expect(padPurchased,"Walk-on countdown did not complete the affordable purchase");
expect(await evaluate(`(()=>{const g=window.__FRUITOPIA__,state=g.core.state,next=g.core.purchasePadById('pad:district:sunny-side-fruit-stand:1','surface');return state.cash===15&&state.purchasePads.transactions.length===1&&state.purchasePads.transactions[0].padId==='pad:district:sunny-side-fruit-stand:0'&&Boolean(next)&&document.querySelector('#cashValue').textContent==='$15'&&document.querySelector('#cashTransaction').textContent.includes('Better Sign');})()`),"Walk-on purchase did not deduct once, update the HUD, persist a transaction, and reveal the next pad");
const padScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-purchase-pads.png",Buffer.from(padScreenshot.data,"base64"));
const frameTiming=await evaluate(`(()=>{const g=__FRUITOPIA__,samples=[];for(let index=0;index<8;index++){const start=performance.now();g.world.draw(performance.now());samples.push(performance.now()-start);}return{average:samples.reduce((a,b)=>a+b,0)/samples.length,max:Math.max(...samples),entities:g.world.entities.length};})()`);expect(frameTiming.average<30,`Large outside map direct draw average too slow: ${frameTiming.average}ms`);expect(frameTiming.max<100,`Large outside map draw spike too slow: ${frameTiming.max}ms`);expect(frameTiming.entities<250,`Region culling rendered too many interactive entities: ${frameTiming.entities}`);

await wait(150);
expect(await evaluate("window.__FRUITOPIA__.world.entities.filter(entity=>entity.type==='manhole').length===4"),"Four discoverable surface manholes were not rendered; the secret Mafia exit must remain hidden");
await evaluate(`(()=>{const game=window.__FRUITOPIA__,entrance=game.Config.SEWER_ENTRANCES[0];game.core.state.player.x=entrance.x;game.core.state.player.y=entrance.y;game.world.findPlayer();game.openPage('manhole',entrance.id);return true;})()`);
let manholeOpened=false;for(let attempt=0;attempt<30&&!manholeOpened;attempt++){await wait(100);manholeOpened=await evaluate("document.querySelector('#dialogTitle')?.textContent==='Fruit Stand Road Manhole'");}expect(manholeOpened,"Approaching and clicking a manhole did not open its interaction");
await evaluate("document.querySelector('[data-do=manhole][data-value=inspect]').click();true");await wait(70);await evaluate("document.querySelector('[data-do=manhole][data-value=open]').click();true");await wait(70);expect(await evaluate("Boolean(document.querySelector('[data-do=enter-sewer]'))"),"Opened manhole lacks Enter Sewer button");await evaluate("document.querySelector('[data-do=enter-sewer]').click();true");await wait(200);
expect(await evaluate("window.__FRUITOPIA__.core.state.sewer.active && !document.querySelector('#sewerHud').classList.contains('hidden')"),"Entering the sewer did not switch to the underground world");let sewerRendered=false;for(let attempt=0;attempt<30&&!sewerRendered;attempt++){await wait(100);sewerRendered=await evaluate("window.__FRUITOPIA__.world.entities.some(entity=>entity.type==='sewer-pump') && window.__FRUITOPIA__.world.entities.some(entity=>entity.type==='water-point')");}expect(sewerRendered,"Explorable sewer objects were not rendered");

await evaluate("(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.player={x:120,y:105,section:'maze-entrance'};g.core.state.sewer.maze.crossedStartLine=false;g.core.updateSewerLocation();g.openPage('sewer-object','sewer-map:entrance-map');return true;})()");await wait(60);expect(await evaluate("Boolean(document.querySelector('.maze-map'))"),"Entrance-only full maze map did not render at the entrance");await evaluate("(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.player={x:140,y:89,section:'red-pipe-quarter'};g.core.updateSewerLocation();g.openPage('sewer-object','sewer-map:entrance-map');return true;})()");await wait(60);expect(await evaluate("!document.querySelector('.maze-map') && document.querySelector('#dialog').textContent.includes('Map unavailable')"),"Full maze map remained available after crossing the start line");

await evaluate(`(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.mafia.invitation=true;g.core.state.sewer.maze.centerOpen=true;g.core.state.sewer.maze.mafiaSymbol=true;g.core.state.cash=100;const joined=g.core.buyMafiaMembership();if(!joined.ok)throw new Error(joined.message);g.openPage('sewer','club');return true;})()`);await wait(80);
expect(await evaluate("document.querySelectorAll('[data-plinko-slot]').length===7 && document.querySelectorAll('[data-plinko-slot]')[3].textContent.includes('JACKPOT')"),"Plinko board or center jackpot is missing");expect(await evaluate("document.querySelector('.private-room').textContent.includes('Mystery Crate') && Boolean(document.querySelector('[data-nav=mafia-game]'))"),"Playable Mystery Crate room is missing from the club");
await evaluate("document.querySelector('[data-nav=mafia-game]').click();true");await wait(80);expect(await evaluate("document.querySelector('#dialogTitle').textContent.includes('Mystery Crate') && document.querySelectorAll('#mafiaOpponents option').length===7 && document.querySelector('[data-do=mafia-start]')"),"Mystery Crate setup did not render");await evaluate("document.querySelector('[data-do=mafia-start]').click();true");await wait(100);expect(await evaluate("(()=>{const g=window.__FRUITOPIA__,human=g.core.state.sewer.mafiaGame.participants.find(p=>p.human);return document.querySelectorAll('.mafia-seat').length===4&&human.hand.length===2&&Boolean(document.querySelector('.mystery-crate'))&&!document.querySelector('[data-do=mafia-attack]');})()"),"Mystery Crate table, starting cards, or event-only attack rule failed");await evaluate("document.querySelector('[data-do=mafia-next]').click();true");await wait(80);expect(await evaluate("window.__FRUITOPIA__.core.state.sewer.mafiaGame.turn===1 && document.querySelector('.mafia-history').textContent.length>0"),"Mystery Crate did not produce and log an event");const mysteryScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-mystery-crate.png",Buffer.from(mysteryScreenshot.data,"base64"));await evaluate("window.__FRUITOPIA__.openPage('sewer','club');true");await wait(60);
await evaluate("document.querySelector('[data-do=plinko-drop]').click();true");await wait(80);expect(await evaluate("(()=>{const g=window.__FRUITOPIA__,ball=document.querySelector('.plinko-ball');return Boolean(ball)&&Number(ball.dataset.slot)===g.core.state.sewer.plinko.pending.visualSlot&&g.core.state.sewer.plinko.pending.slotIndex===g.core.state.sewer.plinko.pending.visualSlot;})()"),"Plinko visual slot does not match its stored reward");await evaluate("(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.plinko.pending.readyAt=g.core.now-1;g.openPage('sewer','club');document.querySelector('[data-do=collect-plinko]').click();return true;})()");await wait(60);expect(await evaluate("window.__FRUITOPIA__.core.state.sewer.plinko.history.length===1"),"Plinko result was not collected exactly once");
await evaluate("(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.mafia.clubChips=10;g.openPage('sewer','club');document.querySelector('[data-do=spin-slots]').click();return true;})()");await wait(80);expect(await evaluate("(()=>{const g=window.__FRUITOPIA__,reels=document.querySelector('.slot-reels');return reels.dataset.reels===g.core.state.sewer.slots.pending.visualReels.join('')&&g.core.state.sewer.slots.pending.reels.join('')===g.core.state.sewer.slots.pending.visualReels.join('');})()"),"Fruit slot visual reels do not match their stored result");await evaluate("(()=>{const g=window.__FRUITOPIA__;g.core.state.sewer.slots.pending.readyAt=g.core.now-1;g.openPage('sewer','club');document.querySelector('[data-do=collect-slots]').click();return true;})()");await wait(60);expect(await evaluate("window.__FRUITOPIA__.core.state.sewer.slots.history.length===1"),"Fruit slot result was not collected exactly once");
await evaluate("(()=>{const g=window.__FRUITOPIA__;g.openPage('sewer','overview');document.querySelector('[data-do=leave-sewer]').click();return true;})()");await wait(100);expect(await evaluate("!window.__FRUITOPIA__.core.state.sewer.active && document.querySelector('#sewerHud').classList.contains('hidden')"),"Returning to the surface failed");

await evaluate("document.querySelector('[data-nav=company]').click();true");await wait(100);
expect(await evaluate("document.querySelector('#dialogTitle').textContent==='Fruitopia Company' && document.querySelectorAll('[data-nav=district]').length===8"),"Company districts screen missing");
await evaluate("document.querySelector('[data-do=subpage][data-value=buildings]').click();true");await wait(100);
expect(await evaluate("document.querySelectorAll('[data-building-card]').length===106"),"Company screen must expose all 106 buildings");
await evaluate("document.querySelector('#buildingCategory').value='Fruit Labs';document.querySelector('#buildingCategory').dispatchEvent(new Event('change',{bubbles:true}));true");
expect(await evaluate("[...document.querySelectorAll('[data-building-card]:not(.hidden)')].length===10"),"Building category filter failed");
await evaluate("document.querySelector('[data-action=close-dialog]').click();true");

await evaluate(`(()=>{const game=window.__FRUITOPIA__,tree=game.core.state.trees[0];game.core.state.player.x=tree.x-1;game.core.state.player.y=tree.y;game.world.findPlayer();game.openPage('tree',tree.id);return true;})()`);
let treeOpened=false;for(let attempt=0;attempt<30&&!treeOpened;attempt++){await wait(100);treeOpened=await evaluate("document.querySelector('#dialogTitle')?.textContent==='Apple Tree'");}
expect(treeOpened,"Click-to-walk tree interaction did not open");
await evaluate("document.querySelector('[data-do=harvest-tree]').click();true");await wait(100);
expect(await evaluate("window.__FRUITOPIA__.core.state.stats.harvested>=1"),"Tree harvest failed");

await evaluate("document.querySelector('[data-action=close-dialog]').click();document.querySelector('[data-nav=recipes]').click();true");await wait(100);
expect(await evaluate("document.querySelectorAll('[data-do=craft]').length===21"),"All 21 recipes missing");
await evaluate("document.querySelector('[data-action=close-dialog]').click();document.querySelector('[data-nav=phone]').click();true");
expect(await evaluate("document.querySelector('#dialog').textContent.includes('Smartphone locked') && document.querySelector('[data-do=go-office-upgrades]')"),"Locked phone must explain exact upgrades");

await evaluate(`(()=>{const game=window.__FRUITOPIA__;for(const id of ['basic-desk-phone','fruitopia-smartphone'])if(!game.core.state.office.upgrades.includes(id))game.core.state.office.upgrades.push(id);game.core.updatePhone();game.core.pushPhoneNotification('order','browser-order','Order waiting','Open the order desk.','orders');game.openPage('phone','home');return true;})()`);await wait(100);
expect(await evaluate("document.querySelectorAll('.phone-folders button').length===5 && document.querySelector('.phone-status').textContent.includes('Fruitopia') && document.querySelector('.phone-company-strip').textContent.includes('reputation') && document.querySelectorAll('.phone-notification').length>=1 && Boolean(document.querySelector('[data-phone-app=orders] i'))"),"Smartphone home, folders, status, or notification badges are incomplete");
expect(await evaluate("document.querySelectorAll('.phone-badge-cluster .phone-mini-badge').length===6 && document.querySelector('.nav-phone').getAttribute('aria-label').includes('active orders')"),"Main Smartphone navigation is missing its six saved activity badges");
await evaluate("[...document.querySelectorAll('.phone-notification')].find(item=>item.textContent.includes('Order waiting')).querySelector('[data-do=open-notification]').click();true");await wait(60);expect(await evaluate("document.querySelector('.phone-content').textContent.includes('Customer Orders')"),"Notification did not open the correct app");
expect(await evaluate("document.querySelectorAll('.order-status-tabs button').length===6 && document.querySelector('.phone-content').textContent.includes('Current stock')"),"Orders app is missing statuses or full order details");
const phoneScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-smartphone-orders.png",Buffer.from(phoneScreenshot.data,"base64"));
const appResults=await evaluate(`(()=>{const results={};for(const app of __FRUITOPIA__.Config.PHONE_APPS_EXPANDED){__FRUITOPIA__.openPage('phone',app.id);const content=document.querySelector('.phone-content');results[app.id]=Boolean(content&&content.textContent.trim().length>0);}return results;})()`);
expect(Object.keys(appResults).length===27&&Object.values(appResults).every(Boolean),`One or more Smartphone apps failed: ${JSON.stringify(appResults)}`);
await evaluate("window.__FRUITOPIA__.openPage('phone','deliveries');true");await wait(40);expect(await evaluate("document.querySelector('[data-do=route-page][data-value=deliveries]').disabled && document.querySelector('.phone-content').textContent.includes('Remote dispatch locked')"),"Phone delivery dispatch bypassed Remote Management");
await evaluate("window.__FRUITOPIA__.openPage('phone','upgrade-planner');true");await wait(40);await evaluate("document.querySelector('#phoneUpgradeSearch').value='Striped Awning';document.querySelector('#phoneUpgradeSearch').dispatchEvent(new Event('change',{bubbles:true}));true");await wait(60);expect(await evaluate("document.querySelector('.phone-upgrade-results [data-upgrade-card] h3')?.textContent==='Striped Awning'"),"Smartphone Upgrade Planner search failed");await evaluate("document.querySelector('[data-do=upgrade-buy]')?.click();true");await wait(50);expect(await evaluate("[...document.querySelectorAll('.toast')].some(item=>item.textContent.includes('Remote Management'))"),"Smartphone Upgrade Planner bypassed Remote Management");
await evaluate("window.__FRUITOPIA__.openPage('phone','sewer-journal');true");await wait(40);expect(await evaluate("document.querySelector('.phone-content').textContent.includes('complete maze map is hidden') && !document.querySelector('.maze-map')"),"Smartphone improperly revealed the sewer maze");
await evaluate("window.__FRUITOPIA__.openPage('phone','fruit-mafia-club');true");await wait(40);expect(await evaluate("document.querySelector('.phone-content').textContent.includes('Remote records only') && !document.querySelector('[data-do=mafia-start]')"),"Fruit Mafia phone app did not respect physical-club-only gameplay");
await evaluate("window.__FRUITOPIA__.openPage('phone','settings');true");await wait(40);expect(await evaluate("document.querySelectorAll('.phone-theme-grid button').length===10"),"Phone themes are incomplete");await evaluate("document.querySelector('[data-do=phone-theme][data-id=cosmic-space]').click();true");await wait(50);expect(await evaluate("__FRUITOPIA__.core.state.phone.theme==='cosmic-space'"),"Phone theme did not persist in state");await evaluate("document.querySelector('[data-do=setting][data-id=colorblindMode]').click();true");await wait(50);expect(await evaluate("document.body.classList.contains('colorblind-mode') && __FRUITOPIA__.core.state.settings.colorblindMode"),"Colorblind-friendly patterns did not activate");await evaluate("document.querySelector('[data-do=setting][data-id=highContrast]').click();true");await wait(50);expect(await evaluate("document.body.classList.contains('high-contrast') && __FRUITOPIA__.core.state.settings.highContrast"),"High-contrast mode did not activate");

await evaluate("document.querySelector('[data-action=close-dialog]').click();window.__FRUITOPIA__.core.state.districts['sunny-side-fruit-stand'].upgrades=[0,1,2,3];document.querySelector('[data-nav=arcade]').click();true");await wait(100);
expect(await evaluate("document.querySelectorAll('[data-do=start-minigame]').length===27 && document.querySelectorAll('.arcade-category').length===7"),"All 27 playable minigames or seven arcade categories are missing");
expect(await evaluate("getComputedStyle(document.documentElement).getPropertyValue('--fruitopia-green').trim()==='#43C96B' && getComputedStyle(document.documentElement).getPropertyValue('--research-cyan').trim()==='#54D9E8' && getComputedStyle(document.documentElement).getPropertyValue('--mafia-gold').trim()==='#E8B640'"),"Core color tokens were not applied to the interface");
const allInstructionScreens=await evaluate(`(()=>{const g=__FRUITOPIA__,results={};for(const game of g.Config.MINIGAMES){g.openPage('arcade','detail:'+game.id,true);results[game.id]=Boolean(document.querySelector('.minigame-detail')&&document.querySelectorAll('.difficulty-card').length===4&&document.querySelector('.minigame-instructions').textContent.includes('Controls'));}g.openPage('arcade');return results;})()`);expect(Object.keys(allInstructionScreens).length===27&&Object.values(allInstructionScreens).every(Boolean),`One or more minigame instruction screens failed: ${JSON.stringify(allInstructionScreens)}`);
const arcadeScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-arcade-colors.png",Buffer.from(arcadeScreenshot.data,"base64"));
await evaluate("document.querySelector('[data-do=start-minigame][data-id=the-big-ask]').click();true");await wait(150);
expect(await evaluate("document.querySelector('.minigame-detail').textContent.includes('How to play') && document.querySelectorAll('.difficulty-card').length===4 && document.querySelector('.minigame-detail').textContent.includes('Minigame quest')"),"Minigame instruction or difficulty screen is incomplete");
const minigameDetailScreenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-minigame-detail.png",Buffer.from(minigameDetailScreenshot.data,"base64"));
await evaluate("document.querySelector('[data-do=launch-minigame]').click();true");await wait(150);
expect(await evaluate("document.querySelector('#minigameMount')?.classList.contains('minigame-stage')"),"Minigame did not start");
expect(await evaluate("document.querySelector('.mini-score') && document.querySelector('.mini-streak') && document.querySelector('.mini-time') && document.querySelector('.mini-pause')"),"Minigame HUD is missing score, streak, timer, or pause");
await evaluate("document.querySelector('.mini-pause').click();true");await wait(30);expect(await evaluate("document.querySelector('.minigame-pause-overlay:not(.hidden)')!==null"),"Minigame pause support failed");await evaluate("document.querySelector('.mini-pause').click();true");
await evaluate("document.querySelector('[data-do=end-minigame]').click();true");await wait(50);
expect(await evaluate("document.querySelector('#minigameMount').textContent.includes('RUN COMPLETE') && document.querySelectorAll('.reward-pills span').length>=3"),"Minigame result screen or reward colors are incomplete");
await evaluate("document.querySelector('#minigameMount button.primary-button').click();true");await wait(50);
const minigameRuns=await evaluate("window.__FRUITOPIA__.core.state.minigames.runs");expect(minigameRuns===1,"Minigame reward not recorded once");

await evaluate("document.querySelector('[data-action=close-dialog]').click();document.querySelector('[data-nav=office]').click();true");await wait(100);
expect(await evaluate("document.querySelectorAll('.office-object').length===17 && Boolean(document.querySelector('#officePlayer')) && document.querySelectorAll('.office-purchase-pad').length>=1"),"Walkable office must include 17 objects and synchronized furniture purchase pads");

const layouts=[];
for(const [width,height,label] of [[1440,900,"desktop"],[900,1024,"tablet"],[390,844,"mobile"]]){
  await command("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:label==="mobile"});await evaluate("__FRUITOPIA__.core.state.upgradeCenter.search='';__FRUITOPIA__.core.state.upgradeCenter.region='all';__FRUITOPIA__.core.state.upgradeCenter.filters={affordable:false,available:false,locked:false,purchased:false};window.__FRUITOPIA__.openPage('upgrades','company-buildings');true");await wait(160);
  const upgradeLayout=await evaluate(`({overflow:document.documentElement.scrollWidth>innerWidth+1,dialogOverflow:document.querySelector('#dialog').scrollWidth>document.querySelector('#dialog').clientWidth+1,center:Boolean(document.querySelector('.upgrade-center')),columns:getComputedStyle(document.querySelector('.upgrade-grid')).gridTemplateColumns.split(' ').filter(Boolean).length})`);expect(!upgradeLayout.overflow&&!upgradeLayout.dialogOverflow&&upgradeLayout.center,`${label} Upgrade Center layout overflowed`);if(label==="mobile")expect(upgradeLayout.columns===1,"Mobile Upgrade Center must use one column");else expect(upgradeLayout.columns===2,`${label} Upgrade Center must use two columns`);
  await evaluate("window.__FRUITOPIA__.openPage('phone','home');true");await wait(100);const phoneLayout=await evaluate("({overflow:document.documentElement.scrollWidth>innerWidth+1,dialogOverflow:document.querySelector('#dialog').scrollWidth>document.querySelector('#dialog').clientWidth+1,device:Boolean(document.querySelector('.phone-device')),folders:document.querySelectorAll('.phone-folders button').length})");expect(!phoneLayout.overflow&&!phoneLayout.dialogOverflow&&phoneLayout.device&&phoneLayout.folders===5,`${label} Smartphone layout overflowed or lost folders`);
  await evaluate("window.__FRUITOPIA__.openPage('map','overview');true");await wait(100);
  const layout=await evaluate(`({label:${JSON.stringify(label)},overflow:document.documentElement.scrollWidth>innerWidth+1,dialogOverflow:document.querySelector('#dialog').scrollWidth>document.querySelector('#dialog').clientWidth+1,mapVisible:Boolean(document.querySelector('.country-map')),navVisible:getComputedStyle(document.querySelector('#mainNav')).display!=='none',touchVisible:getComputedStyle(document.querySelector('#touchPad')).display,upgradeColumns:${label==="mobile"?1:2}})`);layouts.push(layout);expect(!layout.overflow,`${label} has horizontal page overflow`);expect(!layout.dialogOverflow,`${label} dialog overflows horizontally`);expect(layout.mapVisible,`${label} country map hidden`);expect(layout.navVisible,`${label} navigation hidden`);if(label==="mobile")expect(layout.touchVisible==="grid","Mobile touch controls hidden");
  await evaluate("(()=>{document.querySelector('[data-action=close-dialog]').click();const g=window.__FRUITOPIA__,pad=g.core.purchasePadCatalog('surface')[0];g.core.state.player.x=pad.x-5;g.core.state.player.y=pad.y;g.world.findPlayer();g.world.refreshPurchasePads();return true;})()");await wait(280);const padLayout=await evaluate("(()=>{const panel=document.querySelector('#purchasePadPanel'),rect=panel.getBoundingClientRect();return{visible:!panel.classList.contains('hidden'),overflow:document.documentElement.scrollWidth>innerWidth+1,panelOverflow:panel.scrollWidth>panel.clientWidth+1,width:rect.width,viewport:innerWidth};})()");expect(padLayout.visible&&!padLayout.overflow&&!padLayout.panelOverflow&&padLayout.width<=padLayout.viewport,`${label} purchase-pad panel overflowed or disappeared`);
}
await command("Emulation.clearDeviceMetricsOverride");

await evaluate("window.__FRUITOPIA__.openPage('more','settings');true");await wait(60);await evaluate(`(()=>{const dialog=document.querySelector('#dialog'),focus=[...dialog.querySelectorAll("button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex='0']")];focus.at(-1).focus();return focus.at(-1)===document.activeElement;})()`);
await command("Input.dispatchKeyEvent",{type:"keyDown",key:"Tab",code:"Tab",windowsVirtualKeyCode:9});await command("Input.dispatchKeyEvent",{type:"keyUp",key:"Tab",code:"Tab",windowsVirtualKeyCode:9});
expect(await evaluate("document.querySelector('#dialog').contains(document.activeElement)"),"Dialog focus escaped");
await command("Input.dispatchKeyEvent",{type:"keyDown",key:"Escape",code:"Escape",windowsVirtualKeyCode:27});await command("Input.dispatchKeyEvent",{type:"keyUp",key:"Escape",code:"Escape",windowsVirtualKeyCode:27});
expect(await evaluate("document.querySelector('#dialogLayer').classList.contains('hidden')"),"Escape did not close dialog");

expect(exceptions.length===0,`Runtime exceptions:\n${exceptions.join("\n")}`);expect(consoleErrors.length===0,`Console errors:\n${consoleErrors.join("\n")}`);
const screenshot=await command("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});await writeFile("/tmp/fruitopia-tycoon-smoke.png",Buffer.from(screenshot.data,"base64"));
browser.close();console.log(JSON.stringify({ok:true,initial,layouts,screenshot:"/tmp/fruitopia-tycoon-smoke.png"},null,2));
