import * as THREE from "../node_modules/three/build/three.module.min.js";
import * as Config from "./config.js";

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const distance=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
const pointSegmentDistance=(point,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],length=dx*dx+dy*dy||1,t=clamp(((point.x-a[0])*dx+(point.y-a[1])*dy)/length,0,1);return Math.hypot(point.x-(a[0]+dx*t),point.y-(a[1]+dy*t));};
const colorForPad=pad=>({available:0x43c96b,unaffordable:0xf2555f,locked:0xffc247,"under-construction":0x3f8cff,"ready-to-collect":0x54d9e8,completed:0x5e6878,secret:0x7d4dcc,mafia:0x171717,mountain:0xe9f4ff,sewer:0x62c34d,landmark:0xe8b640}[pad?.palette]||({available:0x43c96b,locked:0xffc247,completed:0x5e6878}[pad?.status]||0x43c96b));
const labelForCamera=distance=>distance<.65?"First Person":distance<5.5?"Close Third Person":distance<12.5?"Third Person":"Wide Third Person";
const seeded=(seed,index=0)=>{let value=(seed*9301+49297+index*233)%233280;return value/233280;};

/**
 * The perspective world is a view/controller for the existing FruitopiaCore.
 * Economy, unlocks, interaction results, and persistence remain data-driven in core.js.
 */
export class FruitopiaWorld{
  constructor(canvas,core,{onInteract=()=>{},onMove=()=>{},onPrompt=()=>{},onPadProximity=()=>{},onActivate=()=>{}}={}){
    this.canvas=canvas;this.core=core;this.onInteract=onInteract;this.onMove=onMove;this.onPrompt=onPrompt;this.onPadProximity=onPadProximity;this.onActivate=onActivate;
    this.keys=new Set();this.timedMoves=new Map();this.entities=[];this.purchasePads=[];this.activePurchasePad=null;this.purchaseProgress=null;this.purchaseAnimations=[];this.interactiveMeshes=[];this.cameraBlockers=[];this.colliders=[];this.cullables=[];this.target=null;this.targetedEntity=null;this.highlighted=null;this.walkPhase=0;this.playerVelocityY=0;this.playerJump=0;this.running=true;this.last=performance.now();this.lastBuildAt=0;this.buildSignature="";this.worldMode=core.state.sewer.active?"sewer":"surface";this.drag=null;this.pointerLocked=false;this.gamepadButtons={};this.previewGroup=null;this.focusPoint=null;
    this.camera={x:this.player.x,y:this.player.y,zoom:core.state.camera.zoom||3.2};
    this.targetDistance=clamp(Number(core.state.camera.distance)||10,0,22);this.currentDistance=this.targetDistance;this.yaw=Number(core.state.camera.yaw)||0;this.pitch=clamp(Number(core.state.camera.pitch)||-.18,-.95,.5);
    this.scene=new THREE.Scene();this.perspectiveCamera=new THREE.PerspectiveCamera(67,1,.05,1200);this.raycaster=new THREE.Raycaster();this.centerPointer=new THREE.Vector2(0,0);this.clock=new THREE.Clock();
    this.webgl=true;try{this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:"high-performance"});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;}catch{this.webgl=false;this.ctx=canvas.getContext("2d");}
    this.root=new THREE.Group();this.dynamicRoot=new THREE.Group();this.scene.add(this.root,this.dynamicRoot);this.makeLights();this.bind();this.resize();this.refreshPurchasePads();this.rebuild(true);this.frame=requestAnimationFrame(time=>this.loop(time));
  }
  get state(){return this.core.state;}
  get player(){return this.state.sewer?.active?this.state.sewer.player:this.state.player;}
  bounds(){return this.state.sewer?.active?Config.SEWER_WORLD:Config.OUTSIDE_WORLD;}
  qualitySegments(base=12){return this.state.settings.modelQuality==="low"?Math.max(5,Math.floor(base*.5)):this.state.settings.modelQuality==="medium"?Math.max(7,Math.floor(base*.75)):base;}
  renderDistance(){return({low:85,medium:150,high:260})[this.state.settings.renderDistance]||260;}
  terrainHeight(x,z){if(this.state.sewer?.active)return 0;const rolling=Math.sin(x*.035)*.24+Math.cos(z*.028)*.18;let mountain=0;if(z<165)mountain=(165-z)*.026+Math.max(0,Math.sin(x*.052)+.25)*(165-z)*.013;if(z<45)mountain+=(45-z)*.055;return rolling+mountain;}
  makeLights(){this.ambient=new THREE.HemisphereLight(0xcaf2ff,0x38552e,1.65);this.sun=new THREE.DirectionalLight(0xfff1cb,2.4);this.sun.position.set(90,150,120);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-95;this.sun.shadow.camera.right=95;this.sun.shadow.camera.top=95;this.sun.shadow.camera.bottom=-95;this.scene.add(this.ambient,this.sun);}
  material(color,options={}){return new THREE.MeshStandardMaterial({color,roughness:options.roughness??.78,metalness:options.metalness??.04,transparent:Boolean(options.transparent),opacity:options.opacity??1,emissive:options.emissive??0x000000,emissiveIntensity:options.emissiveIntensity??0,side:options.side??THREE.FrontSide,vertexColors:Boolean(options.vertexColors)});}
  addMesh(geometry,material,x,y,z,parent=this.root,{cast=true,receive=true}={}){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=cast;mesh.receiveShadow=receive;parent.add(mesh);return mesh;}
  label(text,{color="#ffffff",background="rgba(18,39,35,.88)",width=320,height=72,scale=7}={}){const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");ctx.fillStyle=background;ctx.beginPath();ctx.roundRect(2,2,width-4,height-4,16);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.45)";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=color;ctx.font="900 28px system-ui, sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(text).slice(0,28),width/2,height/2);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:true}));sprite.scale.set(scale,scale*height/width,1);return sprite;}
  tag(object,entity){object.userData.entity=entity;this.interactiveMeshes.push(object);return object;}
  register(entity,object=null){this.entities.push(entity);if(object)this.tag(object,entity);return entity;}
  addCollider(x,z,radius,kind="solid",mesh=null){this.colliders.push({x,y:z,radius,kind});if(mesh)this.cameraBlockers.push(mesh);}
  clearGroup(group){while(group.children.length){const child=group.children.pop();child.traverse?.(item=>{item.geometry?.dispose?.();if(item.material){const materials=Array.isArray(item.material)?item.material:[item.material];for(const material of materials){material.map?.dispose?.();material.dispose?.();}}});}}
  makeTerrain(){const geometry=new THREE.PlaneGeometry(Config.OUTSIDE_WORLD.width,Config.OUTSIDE_WORLD.height,72,50),position=geometry.attributes.position,colors=[];const fallback=new THREE.Color(0x78b963);for(let index=0;index<position.count;index++){const wx=position.getX(index)+Config.OUTSIDE_WORLD.width/2,wz=Config.OUTSIDE_WORLD.height/2-position.getY(index),height=this.terrainHeight(wx,wz);position.setZ(index,height);const region=Config.OUTSIDE_REGIONS.find(item=>wx>=item.x-item.w/2&&wx<=item.x+item.w/2&&wz>=item.y-item.h/2&&wz<=item.y+item.h/2);const unlocked=region&&this.state.outside.regions[region.id]?.unlocked,color=region?new THREE.Color(unlocked?region.color:0x69766c):fallback.clone();color.offsetHSL(0,0,(seeded(index)-.5)*.035);colors.push(color.r,color.g,color.b);}geometry.setAttribute("color",new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();const ground=this.addMesh(geometry,this.material(0xffffff,{vertexColors:true,roughness:1}),360,0,250,this.root,{cast:false,receive:true});ground.rotation.x=-Math.PI/2;ground.name="Fruitopia rolling terrain";this.cameraBlockers.push(ground);
    const ocean=this.addMesh(new THREE.PlaneGeometry(600,95,1,1),this.material(0x48c4d4,{transparent:true,opacity:.88,roughness:.28,metalness:.1}),420,-.45,474,this.root,{cast:false,receive:true});ocean.rotation.x=-Math.PI/2;
    for(const [x,z,w,d] of [[78,305,150,4],[205,385,250,3]]){const river=this.addMesh(new THREE.PlaneGeometry(w,d),this.material(0x50bde3,{transparent:true,opacity:.8,roughness:.25}),x,this.terrainHeight(x,z)+.04,z,this.root,{cast:false,receive:true});river.rotation.x=-Math.PI/2;}
    for(let index=0;index<19;index++){const x=22+index*37,z=38+(index%4)*28,height=10+(index%5)*5,radius=9+(index%4)*4,mountain=this.addMesh(new THREE.ConeGeometry(radius,height,this.qualitySegments(8)),this.material(index%3===0?0x728d81:0x607b66,{roughness:1}),x,this.terrainHeight(x,z)+height/2-1,z);mountain.castShadow=true;this.addCollider(x,z,radius*.48,"mountain",mountain);this.cullables.push({object:mountain,x,z,far:430});}}
  makeRoads(){for(const path of Config.OUTSIDE_PATHS){const progress=this.state.outside.roads[path.id],open=progress?.repaired||progress?.discovered||this.state.outside.shortcuts[path.id]||["water","ferry","cable","rail"].includes(path.type),color={dirt:0xa9784c,paved:0x59646b,town:0xb56d5e,bridge:0x9a7250,coastal:0xe6c989,mountain:0x71818b,snow:0xdbeefa,industrial:0x526c78,rail:0x3c4549,cable:0x6c7279,water:0x86d9df,ferry:0x86d9df,portal:0x9c70d7}[path.type]||0x8e765a;for(let index=0;index<path.points.length-1;index++){const a=path.points[index],b=path.points[index+1],dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),mx=(a[0]+b[0])/2,mz=(a[1]+b[1])/2,w=["rail","cable"].includes(path.type)?.7:["water","ferry"].includes(path.type)?1.8:2.5,road=this.addMesh(new THREE.BoxGeometry(w,.12,length),this.material(open?color:0x6f7072,{transparent:!open,opacity:open?1:.48,roughness:.92}),mx,this.terrainHeight(mx,mz)+.12,mz);road.rotation.y=-Math.atan2(dx,dz);road.receiveShadow=true;this.cullables.push({object:road,x:mx,z:mz});if(path.type==="rail"&&index%2===0){for(const side of [-.32,.32]){const rail=this.addMesh(new THREE.BoxGeometry(.08,.12,length),this.material(0x2c3035,{metalness:.72}),mx,this.terrainHeight(mx,mz)+.23,mz);rail.rotation.y=-Math.atan2(dx,dz);rail.translateX(side);}}}}}
  makeTree(tree,index=0,parent=this.root,decorative=false){const group=new THREE.Group(),height=2.25+(index%3)*.16;const trunk=this.addMesh(new THREE.CylinderGeometry(.22,.3,height,this.qualitySegments(8)),this.material(0x704828),0,height/2,0,group);const crown=this.addMesh(new THREE.SphereGeometry(1.25,this.qualitySegments(12),this.qualitySegments(8)),this.material(tree.golden?0xffd34e:tree.diseased?0xa69a51:0x4c9f4c),0,height+1,0,group);if(!decorative&&["ripe","golden"].includes(tree.status))for(let fruit=0;fruit<5;fruit++){const angle=fruit*1.27+index*.2,apple=this.addMesh(new THREE.SphereGeometry(.16,this.qualitySegments(8),6),this.material(tree.golden?0xffd34e:0xe84642,{roughness:.45}),Math.cos(angle)*.9,height+.85+Math.sin(fruit*2.4)*.55,Math.sin(angle)*.82,group);apple.userData.fruit=true;}group.position.set(tree.x,this.terrainHeight(tree.x,tree.y),tree.y);parent.add(group);group.name=decorative?"Orchard tree":`Interactive ${tree.fruit} tree`;if(!decorative){const entity={type:"tree",id:tree.id,x:tree.x,y:tree.y,radius:3,label:`${tree.status==="ripe"||tree.golden?"Pick":"Inspect"} ${Config.FRUIT_BY_ID[tree.fruit]?.name||"fruit"}`};this.register(entity,crown);this.addCollider(tree.x,tree.y,.72,"tree",trunk);}this.cullables.push({object:group,x:tree.x,z:tree.y,far:decorative?125:190});return group;}
  makeCharacter(x,z,{color=0x65a6da,fruit=0xf1c05d,name="Fruitopian",entity=null,scale=1}={}){const group=new THREE.Group(),body=this.addMesh(new THREE.CapsuleGeometry(.38*scale,.72*scale,5,this.qualitySegments(9)),this.material(color),0,1.05*scale,0,group),head=this.addMesh(new THREE.SphereGeometry(.48*scale,this.qualitySegments(12),this.qualitySegments(8)),this.material(fruit,{roughness:.52}),0,1.88*scale,0,group);for(const side of [-1,1]){const leg=this.addMesh(new THREE.CapsuleGeometry(.09*scale,.48*scale,3,6),this.material(0x39454f),side*.18*scale,.38*scale,0,group);leg.name=side<0?"leftLeg":"rightLeg";const arm=this.addMesh(new THREE.CapsuleGeometry(.075*scale,.42*scale,3,6),this.material(color),side*.48*scale,1.12*scale,0,group);arm.rotation.z=side*.15;arm.name=side<0?"leftArm":"rightArm";}const leaf=this.addMesh(new THREE.ConeGeometry(.13*scale,.34*scale,6),this.material(0x459857),.12*scale,2.36*scale,0,group);leaf.rotation.z=-.45;group.position.set(x,this.terrainHeight(x,z),z);group.userData.baseY=group.position.y;group.userData.character=true;if(name){const sprite=this.label(name,{width:280,height:62,scale:2.7*scale});sprite.position.set(0,2.82*scale,0);group.add(sprite);}this.root.add(group);if(entity)this.register(entity,head);this.cullables.push({object:group,x,z,far:95});return group;}
  buildingDimensions(stage=1,large=false){return{w:(large?7:4.7)+stage*1.1,d:(large?6:4)+stage*.7,h:(large?4.8:3.2)+stage*1.15};}
  makeBuilding(x,z,{name="Fruitopia Building",color=0xf3c967,accent=0x684f3b,stage=1,large=false,entity=null,construction=null}={}){const group=new THREE.Group(),size=this.buildingDimensions(stage,large),baseY=this.terrainHeight(x,z);group.position.set(x,baseY,z);const foundation=this.addMesh(new THREE.BoxGeometry(size.w+1,.35,size.d+1),this.material(0xb6aa91),0,.18,0,group);this.cameraBlockers.push(foundation);
    if(construction&&construction.stageIndex<6){const index=construction.stageIndex;if(index>=1){for(const side of [-1,1])for(const front of [-1,1])this.addMesh(new THREE.BoxGeometry(.13,2.6,.13),this.material(0xe2b450),side*size.w*.5,1.35,front*size.d*.5,group);for(let pile=0;pile<4;pile++)this.addMesh(new THREE.BoxGeometry(.75,.22,.32),this.material(pile%2?0x71808a:0x9b6536),-size.w*.35+pile*.7,.28,size.d*.7,group);}if(index>=2)this.addMesh(new THREE.BoxGeometry(size.w,.48,size.d),this.material(0x8e9698),0,.5,0,group);if(index>=3){for(const side of [-1,1])for(const front of [-1,1])this.addMesh(new THREE.BoxGeometry(.15,size.h,.15),this.material(0x8e6944),side*size.w*.47,size.h/2,front*size.d*.47,group);for(let level=1;level<4;level++)this.addMesh(new THREE.BoxGeometry(size.w,.12,size.d),this.material(0xac7e4d),0,level*size.h/4,0,group);}if(index>=4)this.addMesh(new THREE.BoxGeometry(size.w,size.h*.78,size.d),this.material(color),0,size.h*.39,0,group);if(index>=5){const equipment=this.addMesh(new THREE.BoxGeometry(size.w*.55,.8,size.d*.25),this.material(accent,{metalness:.2}),0,1,size.d*.3,group);equipment.name="Equipment installation";}}
    else{const walls=this.addMesh(new THREE.BoxGeometry(size.w,size.h,size.d),this.material(color),0,size.h/2,0,group);const roof=this.addMesh(new THREE.ConeGeometry(Math.max(size.w,size.d)*.72,1.45,4),this.material(accent),0,size.h+.65,0,group);roof.rotation.y=Math.PI/4;for(const side of [-1,1])for(let level=0;level<Math.max(1,Math.min(stage,3));level++){const window=this.addMesh(new THREE.BoxGeometry(.68,.65,.08),this.material(0x8ee9ff,{emissive:0x276b79,emissiveIntensity:.45}),side*size.w*.27,1.25+level*1.15,size.d/2+.05,group);window.name="Lit window";}const door=this.addMesh(new THREE.BoxGeometry(.85,1.45,.11),this.material(0x60483e),0,.75,size.d/2+.07,group);if(stage>=2)this.addMesh(new THREE.BoxGeometry(size.w*.42,size.h*.48,size.d*.65),this.material(new THREE.Color(color).offsetHSL(.03,.02,.08)),size.w*.66,size.h*.24,0,group);if(stage>=3){const tower=this.addMesh(new THREE.CylinderGeometry(.4,.55,2.6,8),this.material(accent,{metalness:.35}),-size.w*.36,size.h+1.5,0,group);this.addMesh(new THREE.SphereGeometry(.34,8,6),this.material(0xffd34e,{emissive:0xe8b640,emissiveIntensity:.5}),-size.w*.36,size.h+2.95,0,group);}this.cameraBlockers.push(walls,roof);if(entity)this.tag(door,entity);}
    const sign=this.label(name,{color:"#fff7d6",background:"rgba(36,55,43,.9)",width:360,height:70,scale:Math.min(5.3,3.6+stage*.3)});sign.position.set(0,size.h+1.55,size.d*.08);group.add(sign);this.root.add(group);this.addCollider(x,z,Math.max(size.w,size.d)*.48,"building",foundation);this.cullables.push({object:group,x,z,far:180});return group;}
  makeSurface(){this.scene.background=new THREE.Color(0x9fdcf0);this.scene.fog=new THREE.Fog(0xb9deda,95,this.renderDistance()+150);this.ambient.color.set(0xcaf2ff);this.ambient.groundColor.set(0x38552e);this.ambient.intensity=1.65;this.sun.visible=true;this.makeTerrain();this.makeRoads();
    for(const tree of this.state.trees)this.makeTree(tree,Number(tree.id.match(/\d+/)?.[0]||0));
    const orchardRegion=Config.OUTSIDE_REGION_BY_ID["apple-grove-hills"];for(let index=0;index<24;index++){const x=orchardRegion.x-orchardRegion.w*.35+(index%8)*8,z=orchardRegion.y-orchardRegion.h*.28+Math.floor(index/8)*8;if(!this.state.trees.some(tree=>Math.hypot(tree.x-x,tree.y-z)<3))this.makeTree({x,y:z,status:"growing"},index,this.root,true);}
    for(const district of Config.DISTRICTS){const progress=this.state.districts[district.id],stage=Math.max(1,(progress?.upgrades?.length||0)/2+1),entity={type:"district",id:district.id,x:district.x,y:district.y,radius:5,label:`Enter ${district.name}`};this.register(entity);this.makeBuilding(district.x,district.y,{name:district.name,color:Config.OUTSIDE_REGION_BY_ID[Config.OUTSIDE_REGIONS.find(region=>Math.abs(region.x-district.x)<40&&Math.abs(region.y-district.y)<35)?.id]?.color||0xf3c967,accent:0x795147,stage:Math.min(4,Math.ceil(stage)),large:true,entity});}
    for(const plot of Config.OUTSIDE_PLOTS){const progress=this.state.outside.plots[plot.id];if(!progress?.unlocked&&!this.state.outside.regions[plot.region]?.discovered)continue;const entity={type:"outside-plot",id:plot.id,x:plot.x,y:plot.y,radius:3,label:progress?.buildingId?`Inspect ${plot.name}`:`Select a building for ${plot.name}`};if(progress?.buildingId){const definition=Config.BUILDING_BY_ID[progress.buildingId]||Config.MOUNTAIN_BUILDING_BY_ID[progress.buildingId],job=this.state.outside.constructionJobs.find(item=>item.plotId===plot.id&&!item.collected),construction=job?this.core.constructionSnapshot(job,Date.now()):null;this.makeBuilding(plot.x,plot.y,{name:definition?.name||plot.name,color:new THREE.Color(Config.OUTSIDE_REGION_BY_ID[plot.region]?.color||0x7cbf72),accent:new THREE.Color(Config.OUTSIDE_REGION_BY_ID[plot.region]?.accent||0x49624d),stage:Math.max(1,progress.level||1),large:["Large","Landmark"].includes(plot.size),entity,construction});if(job)this.makeConstructionCrew(plot.x,plot.y,job,construction);}else{const pad=this.addMesh(new THREE.CylinderGeometry(3.2,3.4,.2,8),this.material(0x879188,{transparent:true,opacity:.62}),plot.x,this.terrainHeight(plot.x,plot.y)+.12,plot.y);this.register(entity,pad);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(7,.05,6)),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.55}));outline.position.set(plot.x,this.terrainHeight(plot.x,plot.y)+.15,plot.y);this.root.add(outline);}}
    this.makeRegionalLandmarks();this.makeSurfacePeople();this.makeManholes();this.makeTransit();this.makeInvestorCenter();this.makePurchasePads("surface");}
  makeConstructionCrew(x,z,job,snapshot){for(let index=0;index<Math.max(1,job.workerIds?.length||1);index++){const worker=this.makeCharacter(x-2+index*1.2,z+4,{color:0x3f8cff,fruit:0xff9f43,name:"",scale:.72});worker.userData.builder=true;}if(snapshot?.ratio<.32){const van=new THREE.Group();this.addMesh(new THREE.BoxGeometry(2.7,.9,1.4),this.material(0x3f8cff),0,.7,0,van);for(const side of [-1,1])for(const front of [-1,1]){const wheel=this.addMesh(new THREE.CylinderGeometry(.26,.26,.18,8),this.material(0x23262b),side*1, .28,front*.72,van);wheel.rotation.x=Math.PI/2;}van.position.set(x-6,this.terrainHeight(x-6,z+5),z+5);this.root.add(van);this.cullables.push({object:van,x:x-6,z:z+5});}}
  makeRegionalLandmarks(){for(const region of Config.OUTSIDE_REGIONS){const progress=this.state.outside.regions[region.id];if(!progress?.discovered)continue;const entity={type:"outside-region",id:region.id,x:region.x,y:region.y,radius:4,label:`Explore ${region.name}`},post=this.addMesh(new THREE.CylinderGeometry(.16,.2,2.7,7),this.material(0x6f4e34),region.x,this.terrainHeight(region.x,region.y)+1.35,region.y);const sign=this.label(`${region.icon} ${region.name}`,{width:390,height:74,scale:6.5});sign.position.set(region.x,this.terrainHeight(region.x,region.y)+4.2,region.y);this.root.add(sign);this.register(entity,post);this.cullables.push({object:sign,x:region.x,z:region.y,far:120});const count=progress.unlocked?Math.min(10,3+Math.floor((progress.completion||0)/15)):2;for(let index=0;index<count;index++){const x=region.x+(seeded(region.index,index)-.5)*region.w*.68,z=region.y+(seeded(region.index+19,index)-.5)*region.h*.62;if(["Valley Floor","Lower Slopes"].includes(region.elevationBand)&&!region.id.includes("industrial")&&!region.id.includes("town")&&!region.id.includes("harbor"))this.makeTree({x,y:z,status:"growing"},index,this.root,true);}}
  }
  makeSurfacePeople(){let index=0;for(const [workerId,employee] of Object.entries(this.state.workers)){const worker=Config.WORKER_BY_ID[workerId],district=Config.DISTRICTS.find(item=>item.name===employee.assignment)||Config.DISTRICTS[index%Config.DISTRICTS.length],x=district.x+4+(index%3)*1.6,z=district.y+4+Math.floor(index/3)*1.6,entity={type:"worker",id:workerId,x,y:z,radius:2,label:`Talk to ${worker?.name||"worker"}`};this.makeCharacter(x,z,{color:0x58a7c5,fruit:[0xe54545,0xf1ca4d,0x8b67d9][index%3],name:worker?.name||"Worker",entity,scale:.83});index++;}
    for(const npc of Config.OUTSIDE_NPCS.slice(0,this.state.settings.modelQuality==="low"?14:30)){const region=Config.OUTSIDE_REGION_BY_ID[npc.region];if(!region||!this.state.outside.regions[npc.region]?.discovered)continue;const nx=region.x+(seeded(region.index,index)-.5)*region.w*.45,nz=region.y+(seeded(region.index+8,index)-.5)*region.h*.4,entity={type:"outside-npc",id:npc.id,x:nx,y:nz,radius:2,label:`Talk to ${npc.name}`};this.makeCharacter(nx,nz,{color:0xe58b73,fruit:0xa9d962,name:npc.name,entity,scale:.75});index++;}}
  makeManholes(){for(const entrance of Config.SEWER_ENTRANCES){const progress=this.state.sewer.entrances[entrance.id];if(entrance.undergroundOnly&&!progress.discovered&&!progress.open)continue;const group=new THREE.Group(),open=progress.open,ring=this.addMesh(new THREE.CylinderGeometry(1.25,1.25,.16,24),this.material(open?0x243a2d:0x606a66,{metalness:.55,roughness:.46}),0,.08,0,group);if(open){ring.material.emissive.setHex(0x2dff68);ring.material.emissiveIntensity=.35;const cover=this.addMesh(new THREE.CylinderGeometry(1.2,1.2,.12,24),this.material(0x59645d,{metalness:.65}),1.3,.75,-.4,group);cover.rotation.z=1.05;for(let rung=0;rung<4;rung++)this.addMesh(new THREE.BoxGeometry(1,.08,.08),this.material(0x9baaa1,{metalness:.6}),0,-.25-rung*.35,0,group);}group.position.set(entrance.x,this.terrainHeight(entrance.x,entrance.y)+.05,entrance.y);this.root.add(group);this.register({type:"manhole",id:entrance.id,x:entrance.x,y:entrance.y,radius:2.6,label:open?`Enter sewer through ${entrance.name}`:`Open ${entrance.name}`},ring);}}
  makeTransit(){for(const station of Config.TRAIN_STATIONS){const progress=this.state.outside.train.stations[station.id];if(!progress?.built)continue;const entity={type:"train-station",id:station.id,x:station.x,y:station.y,radius:3,label:`Use ${station.name}`};this.makeBuilding(station.x,station.y,{name:station.name,color:0x7ec8ff,accent:0x3e7ecb,stage:progress.level||1,entity});}for(const station of Config.CABLE_STATIONS){const progress=this.state.outside.cable.stations[station.id];if(!progress?.built)continue;const entity={type:"cable-station",id:station.id,x:station.x,y:station.y,radius:3,label:`Use ${station.name}`};this.makeBuilding(station.x,station.y,{name:station.name,color:0xe9f4ff,accent:0x55748f,stage:progress.level||1,entity});}
    let index=0;for(const [shipId,owned] of Object.entries(this.state.shipping.ships)){if(!owned)continue;const ship=Config.SHIPPING_FLEET.find(item=>item.id===shipId),group=new THREE.Group();this.addMesh(new THREE.BoxGeometry(5,.9,2),this.material(0x397a9d),0,.8,0,group);this.addMesh(new THREE.BoxGeometry(2,1.2,1.6),this.material(0xf2f4e6),-.5,1.75,0,group);this.addMesh(new THREE.ConeGeometry(.25,3,6),this.material(0x4c4e50,{metalness:.45}),0,3,0,group);const x=166+index*7,z=486-index%2*5;group.position.set(x,.1,z);this.root.add(group);const sprite=this.label(ship?.name||shipId,{scale:4.5,width:300,height:64});sprite.position.set(0,5,0);group.add(sprite);index++;}}
  makeInvestorCenter(){const level=this.state.investors.centerLevel,job=this.state.investors.centerConstruction;if(!level&&!job)return;const x=Config.INVESTOR_CENTER_POSITION.x,z=Config.INVESTOR_CENTER_POSITION.y,construction=job?this.core.constructionSnapshot(job,Date.now()):null;this.makeBuilding(x,z,{name:Config.INVESTOR_CENTER_STAGES[Math.max(0,(job?.level||level)-1)]?.name||"Investor Center",color:0x263840,accent:0xe8b640,stage:Math.max(1,job?.level||level),large:true,construction});for(const investor of Config.INVESTORS.filter(item=>this.state.investors.purchased[item.id])){const stars=this.state.investors.stars[investor.id]||0,definition=Config.INVESTOR_STAR_LEVELS[stars],rates=this.core.incomeOverview().rows.filter(row=>investor.sources.includes(row.id)),rate=rates.reduce((sum,row)=>sum+row.perSecond,0),entity={type:"investor",id:investor.id,x:investor.desk.x,y:investor.desk.y,radius:2,label:`Talk to ${investor.name} · ${definition.symbol} ×${definition.multiplier.toFixed(2)} · $${rate.toFixed(2)}/s`};this.makeCharacter(investor.desk.x,investor.desk.y,{color:0x4a1725,fruit:0xe8b640,name:`${investor.name} ${definition.symbol} ×${definition.multiplier.toFixed(2)}`,entity,scale:.82});}}
  makePurchasePads(world){this.purchasePads=this.core.purchasePadCatalog(world);for(const pad of this.purchasePads){if(!Number.isFinite(pad.x)||!Number.isFinite(pad.y))continue;const group=new THREE.Group(),color=colorForPad(pad),base=this.addMesh(new THREE.CylinderGeometry(1.95,2.15,.32,16),this.material(color,{metalness:.35,roughness:.38,emissive:color,emissiveIntensity:.16}),0,.16,0,group),ring=this.addMesh(new THREE.TorusGeometry(1.58,.12,6,24),this.material(pad.palette==="mafia"?0xe8b640:0xffffff,{emissive:color,emissiveIntensity:.45}),0,.38,0,group);ring.rotation.x=Math.PI/2;const icon=this.label(`${pad.icon} ${pad.name}`,{width:360,height:70,scale:5.8,color:pad.palette==="mafia"?"#ffe49a":"#ffffff",background:"rgba(25,38,34,.9)"});icon.position.set(0,2.9,0);group.add(icon);if(pad.status==="available"&&!this.state.settings.reducedMotion){const beam=this.addMesh(new THREE.CylinderGeometry(.1,.55,6,12),this.material(color,{transparent:true,opacity:.14,emissive:color,emissiveIntensity:.7}),0,3.2,0,group,{cast:false,receive:false});beam.name="Purchase beacon";}group.position.set(pad.x,this.state.sewer.active?.04:this.terrainHeight(pad.x,pad.y)+.04,pad.y);this.root.add(group);const entity={...pad,type:"purchase-pad",radius:2.4,label:`Inspect ${pad.name}. ${pad.status==="available"?"Ready to buy":pad.status}`};this.register(entity,base);this.cullables.push({object:group,x:pad.x,z:pad.y,far:95});}}
  makeSewer(){this.scene.background=new THREE.Color(0x071311);this.scene.fog=new THREE.FogExp2(0x071311,.016);this.ambient.color.set(0x83a59b);this.ambient.groundColor.set(0x101813);this.ambient.intensity=.8;this.sun.visible=false;const floorMaterial=this.material(0x35413d,{roughness:1});
    for(const section of Config.SEWER_SECTIONS){const floor=this.addMesh(new THREE.BoxGeometry(section.w,.28,section.h),this.material(section.color,{roughness:.95}),section.x,-.14,section.y);floor.receiveShadow=true;this.cullables.push({object:floor,x:section.x,z:section.y,far:78});const sign=this.label(`${section.icon} ${section.name}`,{width:380,height:68,scale:5.6,color:section.accent});sign.position.set(section.x,3.8,section.y);this.root.add(sign);this.cullables.push({object:sign,x:section.x,z:section.y,far:54});}
    for(const path of Config.SEWER_PATHS)for(let index=0;index<path.length-1;index++){const a=path[index],b=path[index+1],dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),mx=(a[0]+b[0])/2,mz=(a[1]+b[1])/2,floor=this.addMesh(new THREE.BoxGeometry(6,.22,length),floorMaterial,mx,-.1,mz);floor.rotation.y=-Math.atan2(dx,dz);for(const side of [-1,1]){const wall=this.addMesh(new THREE.BoxGeometry(.38,3.6,length),this.material(index%3===0?0x493a32:0x3e4542),mx,1.8,mz);wall.rotation.y=-Math.atan2(dx,dz);wall.translateX(side*3.1);this.cameraBlockers.push(wall);this.cullables.push({object:wall,x:mx,z:mz,far:62});}if(index%2===0){const pipe=this.addMesh(new THREE.CylinderGeometry(.28,.28,length,8),this.material(index%4===0?0xa1443f:index%4===1?0x3c7191:0x81943d,{metalness:.48}),mx,3.2,mz);pipe.rotation.z=Math.PI/2;pipe.rotation.y=-Math.atan2(dz,dx);}}
    for(const room of Config.SEWER_ROOMS){const x1=room.x-room.w/2,x2=room.x+room.w/2,z1=room.y-room.h/2,z2=room.y+room.h/2;for(const [x,z,w,d] of [[room.x,z1,room.w,.45],[room.x,z2,room.w,.45],[x1,room.y,.45,room.h],[x2,room.y,.45,room.h]]){const wall=this.addMesh(new THREE.BoxGeometry(w,3.8,d),this.material(0x493f39),x,1.9,z);this.cameraBlockers.push(wall);}}
    const water=this.addMesh(new THREE.PlaneGeometry(72,13),this.material(0x39ff70,{transparent:true,opacity:.38,emissive:0x20ce61,emissiveIntensity:.7,roughness:.25}),39,.08,109,this.root,{cast:false,receive:false});water.rotation.x=-Math.PI/2;const water2=this.addMesh(new THREE.PlaneGeometry(46,9),water.material.clone(),195,.08,88,this.root,{cast:false,receive:false});water2.rotation.x=-Math.PI/2;
    this.makeSewerObjects();this.makePurchasePads("sewer");}
  machine(x,z,color=0x54d9e8,entity=null,label="Machine"){const group=new THREE.Group(),base=this.addMesh(new THREE.BoxGeometry(1.8,1.8,1.4),this.material(0x5b6568,{metalness:.35}),0,.9,0,group),light=this.addMesh(new THREE.SphereGeometry(.24,8,6),this.material(color,{emissive:color,emissiveIntensity:1}),0,1.45,.76,group);group.position.set(x,0,z);this.root.add(group);if(entity)this.register(entity,base);const sprite=this.label(label,{width:290,height:58,scale:4});sprite.position.set(0,2.7,0);group.add(sprite);return group;}
  makeSewerObjects(){const sewer=this.state.sewer,maze=sewer.maze;
    for(const entrance of Config.SEWER_ENTRANCES){const progress=sewer.entrances[entrance.id];if(!progress.open&&!progress.openedFromUnderground)continue;const entity={type:"sewer-exit",id:entrance.id,x:entrance.sewerX,y:entrance.sewerY,radius:3,label:`Return to surface: ${entrance.name}`},ladder=new THREE.Group();for(let rung=0;rung<8;rung++)this.addMesh(new THREE.BoxGeometry(1.4,.09,.1),this.material(0xb4bbb5,{metalness:.65}),0,.35+rung*.36,0,ladder);for(const side of [-1,1])this.addMesh(new THREE.BoxGeometry(.1,3,.1),this.material(0x8c9690,{metalness:.6}),side*.65,1.55,0,ladder);ladder.position.set(entrance.sewerX,0,entrance.sewerY);this.root.add(ladder);this.register(entity,ladder.children[0]);}
    for(const landmark of Config.SEWER_LANDMARKS){const seen=sewer.discovery.rooms[landmark.section]||["sewer-overview-board","four-pumps","mixing-machine","maze-board"].includes(landmark.id);if(!seen)continue;const entity=landmark.id==="maze-board"?{type:"sewer-map",id:landmark.id,x:landmark.x,y:landmark.y,radius:3,label:"Study the entrance-only maze map"}:landmark.id==="mixing-machine"?{type:"sewer-lab",id:landmark.id,x:landmark.x,y:landmark.y,radius:3,label:"Use the Sewer Test Lab"}:landmark.id==="golden-grape"?{type:"mafia-symbol",id:landmark.id,x:landmark.x,y:landmark.y,radius:3,label:"Inspect Golden Grape symbol"}:null;const object=this.machine(landmark.x,landmark.y,new THREE.Color(landmark.accent||0x54d9e8),entity,`${landmark.icon} ${landmark.name}`);sewer.discovery.landmarks[landmark.id]=true;}
    for(const pump of Config.SEWER_PUMPS)this.machine(pump.x,pump.y,sewer.pumps.states[pump.id]?0x43c96b:0xff9f43,{type:"sewer-pump",id:pump.id,x:pump.x,y:pump.y,radius:2.6,label:pump.name},pump.name);
    for(const point of Config.WATER_POINTS){if(point.requires==="blue-water-emblem"&&!maze.emblems.blue)continue;if(point.requires==="cosmic-age"&&this.state.evolutionAge<5)continue;const ready=sewer.collectionPoints[point.id].readyAt<=Date.now(),pool=this.addMesh(new THREE.CylinderGeometry(1.45,1.6,.12,20),this.material(ready?0x58ff79:0x44564c,{transparent:true,opacity:.85,emissive:ready?0x2ec45b:0x000000,emissiveIntensity:.7}),point.x,.08,point.y);this.register({type:"water-point",id:point.id,x:point.x,y:point.y,radius:2.8,label:ready?`Collect ${point.quality}`:"Water source refilling"},pool);}
    for(const valve of Config.SEWER_VALVES){const open=maze.valves[valve.id],wheel=this.addMesh(new THREE.TorusGeometry(.65,.14,8,18),this.material(open?0x43c96b:0xe05950,{metalness:.65,emissive:open?0x1f8d3d:0x000000,emissiveIntensity:.4}),valve.x,1.15,valve.y);wheel.rotation.y=Math.PI/2;this.register({type:"sewer-valve",id:valve.id,x:valve.x,y:valve.y,radius:2.5,label:valve.name},wheel);}
    for(const gate of Config.SEWER_GATES){const open=maze.gates[gate.id],group=new THREE.Group();for(let bar=-2;bar<=2;bar++)this.addMesh(new THREE.BoxGeometry(.12,3,.12),this.material(open?0x43c96b:0x6a7474,{metalness:.75}),bar*.38,1.5,0,group);group.position.set(gate.x,0,gate.y);group.rotation.y=open?Math.PI/2:0;this.root.add(group);if(!open){this.cameraBlockers.push(...group.children);this.addCollider(gate.x,gate.y,1.5,"gate");}this.register({type:"sewer-gate",id:gate.id,x:gate.x,y:gate.y,radius:2.7,label:open?`${gate.name} open`:gate.name},group.children[0]);}
    for(const shortcut of Config.SEWER_SHORTCUTS)this.machine(shortcut.x,shortcut.y,maze.shortcuts[shortcut.id]?0x43c96b:0x7d4dcc,{type:"sewer-shortcut",id:shortcut.id,x:shortcut.x,y:shortcut.y,radius:2.4,label:shortcut.name},maze.shortcuts[shortcut.id]?`Open · ${shortcut.name}`:`Locked · ${shortcut.name}`);
    for(const treasure of Config.SEWER_TREASURES){if(maze.treasures[treasure.id])continue;const chest=this.addMesh(new THREE.BoxGeometry(1.1,.75,.8),this.material(0xe8b640,{metalness:.3,emissive:0x8a5c12,emissiveIntensity:.35}),treasure.x,.38,treasure.y);this.register({type:"sewer-treasure",id:treasure.id,x:treasure.x,y:treasure.y,radius:2.4,label:treasure.name},chest);}
    const puzzleObjects=[[148,67,"red-puzzle","red","Red Pressure Controls",0xf2555f],[210,75,"blue-puzzle","blue","Blue Water Controls",0x3f8cff],[158,117,"yellow-puzzle","yellow","Yellow Switchboard",0xffd34e],[188,37,"green-puzzle","green","Root Irrigation Controls",0x43c96b],[181,75,"center-machine","center","Four-Color Valve Door",0xe8b640],[138,29,"forgotten-lab","lab","Forgotten Fruit Laboratory",0x9b7bff],[207,12,"sewer-garden","garden","Underground Fruit Garden",0x62c34d],[101,116,"maintenance-wing","maintenance","Maintenance Equipment Cage",0xff9f43]];for(const [x,z,type,id,name,color] of puzzleObjects)this.machine(x,z,color,{type,id,x,y:z,radius:3,label:name},name);
    for(const checkpoint of Config.SEWER_CHECKPOINTS)this.machine(checkpoint.x,checkpoint.y,0xffd34e,{type:"sewer-checkpoint",id:checkpoint.section,x:checkpoint.x,y:checkpoint.y,radius:2.5,label:checkpoint.name},`🔔 ${checkpoint.name}`);
    for(const character of Config.SEWER_CHARACTERS){if(character.x>=199&&!sewer.mafia.membership&&character.id!=="fruit-mafia-bouncer")continue;const entity={type:character.id==="fruit-mafia-bouncer"?"mafia-bouncer":"sewer-character",id:character.id,x:character.x,y:character.y,radius:2.7,label:`Talk to ${character.name}`};this.makeCharacter(character.x,character.y,{color:character.id.includes("mafia")?0x4a1725:0x4f8d76,fruit:character.id.includes("mafia")?0xe8b640:0x7ed66b,name:character.name,entity,scale:.78});}
    if(sewer.mafia.membership)for(const [x,z,type,label,color] of [[216,34,"plinko","Fruit Plinko",0xe8b640],[225,34,"fruit-slots","Fruit Slot Machine",0x9b7bff],[222,47,"future-mafia-game","Fruit Mafia: The Mystery Crate",0x4a1725]])this.machine(x,z,color,{type,id:type,x,y:z,radius:3,label},label);
  }
  rebuild(force=false){const signature=JSON.stringify([this.state.sewer.active,Object.entries(this.state.buildings).map(([id,item])=>[id,item.level,item.state]),this.state.outside.constructionJobs.map(job=>[job.id,job.collected,this.core.constructionSnapshot(job,Date.now()).stageIndex]),Object.values(this.state.outside.plots).map(item=>[item.buildingId,item.level,item.state]),Object.values(this.state.districts).map(item=>item.upgrades.length),this.state.outside.currentRegion,this.state.investors.centerLevel,this.state.investors.centerConstruction?.id,Object.values(this.state.investors.stars),Object.values(this.state.sewer.entrances).map(item=>item.open),Object.values(this.state.sewer.maze.gates),Object.values(this.state.sewer.maze.valves),this.state.settings.modelQuality,this.state.settings.renderDistance]);if(!force&&signature===this.buildSignature)return;this.buildSignature=signature;this.worldMode=this.state.sewer.active?"sewer":"surface";this.clearGroup(this.root);this.entities=[];this.interactiveMeshes=[];this.cameraBlockers=[];this.colliders=[];this.cullables=[];this.previewGroup=null;if(this.state.sewer.active)this.makeSewer();else this.makeSurface();this.makePlayer();this.updatePreview();}
  makePlayer(){this.playerGroup=this.makeCharacter(this.player.x,this.player.y,{color:0x43a4cf,fruit:0xe74e49,name:"You",scale:.92});this.playerGroup.userData.player=true;}
  resize(){const rect=this.canvas.getBoundingClientRect(),width=Math.max(1,Math.round(rect.width*devicePixelRatio)),height=Math.max(1,Math.round(rect.height*devicePixelRatio));if(this.webgl){this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.state.settings.effectsQuality==="low"?1:1.7));this.renderer.setSize(rect.width,rect.height,false);this.renderer.shadowMap.enabled=Boolean(this.state.settings.shadows)&&this.state.settings.effectsQuality!=="low";this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;}else{this.canvas.width=width;this.canvas.height=height;}this.perspectiveCamera.aspect=rect.width/Math.max(1,rect.height);this.perspectiveCamera.updateProjectionMatrix();this.width=rect.width;this.height=rect.height;}
  bind(){this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.canvas);window.addEventListener("keydown",event=>{if(/INPUT|SELECT|TEXTAREA/.test(event.target?.tagName||"")||!document.querySelector("#dialogLayer")?.classList.contains("hidden"))return;const key=event.key.toLowerCase();if(["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright","shift"].includes(key)){this.keys.add(key);event.preventDefault();}if(key==="v"&&!event.repeat){event.preventDefault();this.toggleCamera();}if(key==="e"&&!event.repeat){event.preventDefault();this.interact();}if(event.code==="Space"&&!event.repeat&&!this.activePurchasePad){event.preventDefault();this.jump();}});window.addEventListener("keyup",event=>this.keys.delete(event.key.toLowerCase()));
    this.canvas.addEventListener("wheel",event=>{event.preventDefault();this.setCameraDistance(this.targetDistance+(event.deltaY>0?2:-2));},{passive:false});
    this.canvas.addEventListener("pointerdown",event=>{if(event.button!==0)return;this.canvas.focus();if(this.targetDistance<.65&&!this.pointerLocked&&this.canvas.requestPointerLock){this.canvas.requestPointerLock();return;}this.drag={id:event.pointerId,x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,moved:false};this.canvas.setPointerCapture?.(event.pointerId);});
    this.canvas.addEventListener("pointermove",event=>{if(this.pointerLocked){this.rotateLook(event.movementX,event.movementY);return;}if(!this.drag||this.drag.id!==event.pointerId)return;const dx=event.clientX-this.drag.x,dy=event.clientY-this.drag.y;if(Math.hypot(event.clientX-this.drag.startX,event.clientY-this.drag.startY)>5)this.drag.moved=true;this.rotateLook(dx,dy);this.drag.x=event.clientX;this.drag.y=event.clientY;});
    this.canvas.addEventListener("pointerup",event=>{if(!this.drag)return;const moved=this.drag.moved;this.drag=null;this.canvas.releasePointerCapture?.(event.pointerId);if(!moved&&this.targetedEntity)this.interact();else if(!moved&&this.targetDistance>=.65){const point=this.screenToWorld(event.clientX,event.clientY);if(point)this.target={x:point.x,y:point.y};}});
    document.addEventListener("pointerlockchange",()=>{this.pointerLocked=document.pointerLockElement===this.canvas;this.canvas.classList.toggle("pointer-locked",this.pointerLocked);this.canvas.closest(".world-card")?.classList.toggle("pointer-captured",this.pointerLocked);});
  }
  rotateLook(dx,dy){const sensitivity=(this.state.settings.cameraSensitivity||1)*.0028;this.yaw-=dx*sensitivity;this.pitch=clamp(this.pitch-dy*sensitivity,-.95,.5);this.state.camera.yaw=this.yaw;this.state.camera.pitch=this.pitch;this.focusPoint=null;}
  setCameraDistance(value){const max=this.state.sewer.active?8:18;this.targetDistance=clamp(Number(value)||0,0,max);if(this.targetDistance<.65)this.targetDistance=0;else this.state.camera.normalDistance=clamp(this.targetDistance,5,max);this.state.camera.distance=this.targetDistance;this.state.camera.mode=this.targetDistance<.65?"first-person":"third-person";this.camera.zoom=clamp((31-this.targetDistance)/6.5,1,5);this.state.camera.zoom=this.camera.zoom;const slider=document.querySelector("#cameraDistance");if(slider)slider.value=String(this.targetDistance);this.updateCameraIndicator();}
  toggleCamera(){this.setCameraDistance(this.targetDistance<.65?(this.state.sewer.active?Math.min(7,this.state.camera.normalDistance||7):this.state.camera.normalDistance||10):0);}
  zoom(amount){this.setCameraDistance(this.targetDistance-amount*18);}
  focusAt(x,z){this.focusPoint={x,z,until:performance.now()+4000};this.camera.x=x;this.camera.y=z;}
  findPlayer(){this.focusPoint=null;this.camera.x=this.player.x;this.camera.y=this.player.y;if(this.targetDistance<.65)this.setCameraDistance(this.state.sewer.active?7:this.state.camera.normalDistance||10);}
  clampCamera(){const bounds=this.bounds();this.camera.x=clamp(Number(this.camera.x)||this.player.x,0,bounds.width);this.camera.y=clamp(Number(this.camera.y)||this.player.y,0,bounds.height);if(Math.hypot(this.camera.x-this.player.x,this.camera.y-this.player.y)>3)this.focusAt(this.camera.x,this.camera.y);}
  moveDirection(direction){const key={up:"w",down:"s",left:"a",right:"d"}[direction];if(!key)return;this.timedMoves.set(key,performance.now()+180);const forward={x:Math.sin(this.yaw),z:-Math.cos(this.yaw)},right={x:Math.cos(this.yaw),z:Math.sin(this.yaw)},vector=key==="w"?forward:key==="s"?{x:-forward.x,z:-forward.z}:key==="d"?right:{x:-right.x,z:-right.z},nx=this.player.x+vector.x*.8,nz=this.player.y+vector.z*.8;if(this.canMoveTo(nx,this.player.y))this.player.x=nx;if(this.canMoveTo(this.player.x,nz))this.player.y=nz;this.player.facing=Math.atan2(vector.x,-vector.z);this.onMove(this.player);}
  jump(){if(this.state.sewer.active||this.playerJump>0.02||this.playerVelocityY!==0)return false;this.playerVelocityY=5.4;return true;}
  surfaceAllowed(x,z){if(x<2||z<2||x>Config.OUTSIDE_WORLD.width-2||z>Config.OUTSIDE_WORLD.height-2)return false;const region=Config.OUTSIDE_REGIONS.find(item=>x>=item.x-item.w/2&&x<=item.x+item.w/2&&z>=item.y-item.h/2&&z<=item.y+item.h/2);if(region&&this.state.outside.regions[region.id]?.unlocked)return true;if(Math.hypot(x-57,z-278)<65)return true;for(const path of Config.OUTSIDE_PATHS){const progress=this.state.outside.roads[path.id],open=progress?.repaired||progress?.discovered||this.state.outside.shortcuts[path.id]||["starter-loop","orchard-road","valley-east-road"].includes(path.id);if(!open)continue;for(let index=0;index<path.points.length-1;index++)if(pointSegmentDistance({x,y:z},path.points[index],path.points[index+1])<5.5)return true;}return false;}
  sewerAllowed(x,z){if(x<3||z<3||x>Config.SEWER_WORLD.width-3||z>Config.SEWER_WORLD.height-3)return false;if(Config.SEWER_ROOMS.some(room=>x>room.x-room.w/2+1&&x<room.x+room.w/2-1&&z>room.y-room.h/2+1&&z<room.y+room.h/2-1))return true;return Config.SEWER_PATHS.some(path=>path.some((point,index)=>index<path.length-1&&pointSegmentDistance({x,y:z},point,path[index+1])<2.55));}
  canMoveTo(x,z){if(!(this.state.sewer.active?this.sewerAllowed(x,z):this.surfaceAllowed(x,z)))return false;for(const collider of this.colliders){const safe=collider.kind==="tree"?.72:collider.kind==="gate"?1.25:Math.max(1.1,collider.radius);if(Math.hypot(x-collider.x,z-collider.y)<safe)return false;}return true;}
  updateMovement(dt,now){for(const [key,until] of this.timedMoves)if(until<now)this.timedMoves.delete(key);const pressed=key=>this.keys.has(key)||this.timedMoves.has(key),pad=navigator.getGamepads?.()[0];let forward=(pressed("w")||pressed("arrowup")?1:0)-(pressed("s")||pressed("arrowdown")?1:0),side=(pressed("d")||pressed("arrowright")?1:0)-(pressed("a")||pressed("arrowleft")?1:0);if(pad){if(Math.abs(pad.axes[1]||0)>.18)forward-=pad.axes[1];if(Math.abs(pad.axes[0]||0)>.18)side+=pad.axes[0];if(Math.abs(pad.axes[2]||0)>.2||Math.abs(pad.axes[3]||0)>.2)this.rotateLook((pad.axes[2]||0)*10,(pad.axes[3]||0)*10);const interact=Boolean(pad.buttons?.[0]?.pressed),jump=Boolean(pad.buttons?.[1]?.pressed),view=Boolean(pad.buttons?.[3]?.pressed);if(interact&&!this.gamepadButtons.interact)this.interact();if(jump&&!this.gamepadButtons.jump)this.jump();if(view&&!this.gamepadButtons.view)this.toggleCamera();this.gamepadButtons={interact,jump,view};}
    let moving=false;if(forward||side){const length=Math.hypot(forward,side)||1,fx=Math.sin(this.yaw),fz=-Math.cos(this.yaw),rx=Math.cos(this.yaw),rz=Math.sin(this.yaw),mx=(fx*forward+rx*side)/length,mz=(fz*forward+rz*side)/length,speed=(pressed("shift")?18:11)*(this.state.sewer.active?.78:1),nx=this.player.x+mx*speed*dt,nz=this.player.y+mz*speed*dt;if(this.canMoveTo(nx,this.player.y))this.player.x=nx;if(this.canMoveTo(this.player.x,nz))this.player.y=nz;this.player.facing=Math.atan2(mx,-mz);this.walkPhase+=dt*(pressed("shift")?12:8);moving=true;this.target=null;this.focusPoint=null;this.onMove(this.player);}else if(this.target){const dx=this.target.x-this.player.x,dz=this.target.y-this.player.y,length=Math.hypot(dx,dz);if(length<1){this.target=null;}else{const speed=10,nx=this.player.x+dx/length*Math.min(length,speed*dt),nz=this.player.y+dz/length*Math.min(length,speed*dt);if(this.canMoveTo(nx,nz)){this.player.x=nx;this.player.y=nz;this.player.facing=Math.atan2(dx,-dz);this.walkPhase+=dt*8;moving=true;this.onMove(this.player);}else this.target=null;}}
    if(this.playerVelocityY||this.playerJump){this.playerVelocityY-=12*dt;this.playerJump=Math.max(0,this.playerJump+this.playerVelocityY*dt);if(this.playerJump<=0){this.playerJump=0;this.playerVelocityY=0;}}
    if(this.playerGroup){this.playerGroup.position.set(this.player.x,(this.state.sewer.active?0:this.terrainHeight(this.player.x,this.player.y))+this.playerJump,this.player.y);this.playerGroup.rotation.y=this.player.facing||0;for(const child of this.playerGroup.children){if(child.name==="leftLeg"||child.name==="rightArm")child.rotation.x=moving?Math.sin(this.walkPhase)*.7:0;if(child.name==="rightLeg"||child.name==="leftArm")child.rotation.x=moving?-Math.sin(this.walkPhase)*.7:0;}}
  }
  resolveCameraCollision(target,desired,distanceValue){if(distanceValue<.65)return desired;const direction=desired.clone().sub(target),length=direction.length();if(length<.1)return desired;direction.normalize();this.raycaster.set(target,direction);this.raycaster.near=.2;this.raycaster.far=length;const hit=this.raycaster.intersectObjects(this.cameraBlockers,false).find(item=>item.distance>.35);if(hit)return target.clone().add(direction.multiplyScalar(Math.max(.45,hit.distance-.35)));return desired;}
  updateCamera(dt){const max=this.state.sewer.active?8:18;if(this.targetDistance>max)this.setCameraDistance(max);const easing=this.state.settings.reducedMotion?1:Math.min(1,dt*8);this.currentDistance+=(this.targetDistance-this.currentDistance)*easing;const first=this.currentDistance<.65,playerY=(this.state.sewer.active?0:this.terrainHeight(this.player.x,this.player.y))+this.playerJump,anchor=this.focusPoint&&this.focusPoint.until>performance.now()?new THREE.Vector3(this.focusPoint.x,this.state.sewer.active?1.5:this.terrainHeight(this.focusPoint.x,this.focusPoint.z)+1.5,this.focusPoint.z):new THREE.Vector3(this.player.x,playerY+1.62,this.player.y),forward=new THREE.Vector3(Math.sin(this.yaw),0,-Math.cos(this.yaw));let position,look;
    if(first){position=anchor.clone();look=anchor.clone().add(new THREE.Vector3(Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch)).multiplyScalar(20));}
    else{const orbit=clamp(.28-this.pitch*.55,.08,.72),horizontal=Math.cos(orbit)*this.currentDistance,height=Math.sin(orbit)*this.currentDistance,right=new THREE.Vector3(Math.cos(this.yaw),0,Math.sin(this.yaw));position=anchor.clone().addScaledVector(forward,-horizontal).addScaledVector(right,Math.min(1.15,this.currentDistance*.12));position.y+=height;position=this.resolveCameraCollision(anchor,position,this.currentDistance);const ground=this.state.sewer.active?.3:this.terrainHeight(position.x,position.z)+.35;position.y=Math.max(position.y,ground);look=anchor.clone().addScaledVector(forward,1.6);look.y+=this.pitch*2;}
    if(this.state.settings.reducedMotion)this.perspectiveCamera.position.copy(position);else this.perspectiveCamera.position.lerp(position,Math.min(1,dt*12));this.perspectiveCamera.lookAt(look);this.playerGroup.visible=!first;this.camera.x=anchor.x;this.camera.y=anchor.z;this.state.camera.x=this.player.x;this.state.camera.y=this.player.y;this.state.camera.yaw=this.yaw;this.state.camera.pitch=this.pitch;this.updateCameraIndicator();}
  updateCameraIndicator(){const label=labelForCamera(this.targetDistance),indicator=document.querySelector("#cameraIndicator"),card=this.canvas.closest(".world-card");if(indicator&&indicator.dataset.label!==label){indicator.dataset.label=label;indicator.querySelector("b").textContent=label;}card?.setAttribute("data-camera",this.targetDistance<.65?"first-person":"third-person");const slider=document.querySelector("#cameraDistance");if(slider&&!slider.matches(":active"))slider.value=String(this.targetDistance);}
  targetEntity(){this.raycaster.setFromCamera(this.centerPointer,this.perspectiveCamera);this.raycaster.near=0;this.raycaster.far=this.targetDistance<.65?7.5:11;const hit=this.raycaster.intersectObjects(this.interactiveMeshes,false).find(item=>item.object.userData.entity);if(hit)return hit.object.userData.entity;const player=this.player,forward={x:Math.sin(this.yaw),y:-Math.cos(this.yaw)};return this.entities.filter(entity=>distance(player,entity)<(this.targetDistance<.65?5.5:4.2)).map(entity=>{const dx=entity.x-player.x,dz=entity.y-player.y,length=Math.hypot(dx,dz)||1,dot=(dx/length)*forward.x+(dz/length)*forward.y;return{entity,d:length,dot};}).filter(item=>item.dot>.12).sort((a,b)=>(b.dot-a.dot)*3+a.d-b.d)[0]?.entity||null;}
  interactionText(entity){if(!entity)return this.state.sewer.active?"Explore the tunnels. Colored pipes and landmarks guide you through the sewer.":"Explore Fruitopia in 3D. Approach a tree, worker, building, manhole, or purchase pad.";if(entity.type==="tree")return`Press E to ${entity.label}`;if(["worker","outside-npc","sewer-character","mafia-bouncer"].includes(entity.type))return`Press E to ${entity.label}`;if(entity.type==="manhole")return`Press E to ${entity.label}`;if(entity.type==="sewer-exit")return`Press E to climb to the surface`;if(entity.type==="purchase-pad")return`Press E to inspect ${entity.name} · ${entity.status==="available"?"walk onto the glowing pad to buy":entity.label}`;return`Press E to ${entity.label||"interact"}`;}
  updateTarget(){const entity=this.targetEntity();if(this.highlighted&&this.highlighted!==entity){const mesh=this.interactiveMeshes.find(item=>item.userData.entity===this.highlighted);if(mesh)mesh.scale.setScalar(1);}this.targetedEntity=entity;this.highlighted=entity;if(entity){const mesh=this.interactiveMeshes.find(item=>item.userData.entity===entity);if(mesh)mesh.scale.setScalar(1.09);}document.querySelector("#crosshair")?.classList.toggle("targeting",Boolean(entity));this.onPrompt(this.interactionText(entity));}
  interact(){const entity=this.targetedEntity||this.entities.filter(item=>distance(this.player,item)<3.5).sort((a,b)=>distance(this.player,a)-distance(this.player,b))[0];if(entity)this.onInteract(entity);}
  refreshPurchasePads(){this.purchasePads=this.core.purchasePadCatalog(this.state.sewer.active?"sewer":"surface");this.buildSignature="";}
  setPurchaseProgress(id,ratio){this.purchaseProgress=id?{id,ratio:clamp(ratio||0,0,1)}:null;}
  playPurchaseAnimation(pad){this.purchaseAnimations.push({id:pad.id,x:pad.x,y:pad.y,startedAt:performance.now(),duration:this.state.settings.reducedPurchaseAnimations?450:1600});this.buildSignature="";}
  updatePadProximity(){const nearby=this.purchasePads.filter(pad=>Number.isFinite(pad.x)&&distance(this.player,pad)<7).sort((a,b)=>distance(this.player,a)-distance(this.player,b))[0]||null,changed=nearby?.id!==this.activePurchasePad?.id;this.activePurchasePad=nearby;if(changed)this.updatePreview();this.onPadProximity(nearby,nearby?{distance:distance(this.player,nearby),onPad:distance(this.player,nearby)<=2.25}:{distance:Infinity,onPad:false});}
  updatePreview(){if(this.previewGroup){this.root.remove(this.previewGroup);this.previewGroup=null;}const pad=this.activePurchasePad;if(!pad||!this.state.settings.showBuildingPreviews||!Number.isFinite(pad.x))return;const group=new THREE.Group(),color=colorForPad(pad),x=pad.previewX??pad.x+5,z=pad.previewY??pad.y-4,box=this.addMesh(new THREE.BoxGeometry(5,3.6,4),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.22,wireframe:false}),0,1.8,0,group,{cast:false,receive:false});const edges=new THREE.LineSegments(new THREE.EdgesGeometry(box.geometry),new THREE.LineBasicMaterial({color,transparent:true,opacity:.95}));group.add(edges);const points=[new THREE.Vector3(pad.x,1,pad.y),new THREE.Vector3(x,1,z)],line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color}));this.root.add(line);group.position.set(x,this.state.sewer.active?0:this.terrainHeight(x,z),z);this.root.add(group);group.add(this.label(`PREVIEW · ${pad.name}`,{width:360,height:64,scale:5}));group.children.at(-1).position.set(0,4.5,0);group.userData.line=line;this.previewGroup=group;}
  updateAnimations(now,dt){this.clearGroup(this.dynamicRoot);for(const item of this.cullables){if(item.object.userData.player)continue;const dx=item.x-this.perspectiveCamera.position.x,dz=item.z-this.perspectiveCamera.position.z;item.object.visible=Math.hypot(dx,dz)<(item.far||this.renderDistance());}for(const group of this.root.children.filter(item=>item.userData.builder)){group.position.y=group.userData.baseY+Math.sin(now*.004+group.position.x)*.05;}for(const animation of this.purchaseAnimations){const ratio=(now-animation.startedAt)/animation.duration;if(ratio<1){const ring=this.addMesh(new THREE.TorusGeometry(1+ratio*5,.08,5,30),new THREE.MeshBasicMaterial({color:0x35d07f,transparent:true,opacity:1-ratio}),animation.x,this.state.sewer.active?.2:this.terrainHeight(animation.x,animation.y)+.2,animation.y,this.dynamicRoot,{cast:false,receive:false});ring.rotation.x=Math.PI/2;}}this.purchaseAnimations=this.purchaseAnimations.filter(item=>now-item.startedAt<item.duration);}
  update(dt,now=performance.now()){if(this.worldMode!==(this.state.sewer.active?"sewer":"surface")){this.target=null;this.focusPoint=null;this.setCameraDistance(Math.min(this.targetDistance,this.state.sewer.active?7:18));this.rebuild(true);}if(now-this.lastBuildAt>650){this.lastBuildAt=now;this.rebuild();}this.updateMovement(dt,now);this.scene.updateMatrixWorld(true);this.updateCamera(dt);this.perspectiveCamera.updateMatrixWorld(true);this.updateTarget();this.updatePadProximity();this.updateAnimations(now,dt);}
  draw(now=performance.now()){if(!this.webgl){const ctx=this.ctx;ctx.fillStyle=this.state.sewer.active?"#071311":"#92cde8";ctx.fillRect(0,0,this.canvas.width,this.canvas.height);ctx.fillStyle="#fff";ctx.font="700 18px system-ui";ctx.textAlign="center";ctx.fillText("Fruitopia 3D needs WebGL on this device.",this.canvas.width/2,this.canvas.height/2);return;}this.renderer.render(this.scene,this.perspectiveCamera);}
  loop(now){if(!this.running)return;const dt=Math.min(.05,Math.max(.001,(now-this.last)/1000));this.last=now;this.update(dt,now);this.draw(now);this.frame=requestAnimationFrame(time=>this.loop(time));}
  worldToScreen(x,z){const point=new THREE.Vector3(x,(this.state.sewer.active?0:this.terrainHeight(x,z))+1,z).project(this.perspectiveCamera);return{x:(point.x*.5+.5)*this.width,y:(-.5*point.y+.5)*this.height};}
  screenToWorld(clientX,clientY){const rect=this.canvas.getBoundingClientRect(),pointer=new THREE.Vector2((clientX-rect.left)/rect.width*2-1,-((clientY-rect.top)/rect.height)*2+1);this.raycaster.setFromCamera(pointer,this.perspectiveCamera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),point=new THREE.Vector3();if(!this.raycaster.ray.intersectPlane(plane,point))return null;return{x:clamp(point.x,0,this.bounds().width),y:clamp(point.z,0,this.bounds().height)};}
  scale(){return Math.max(.4,18/Math.max(1,this.currentDistance));}
  isVisible(x,z,pad=14){return Math.hypot(x-this.perspectiveCamera.position.x,z-this.perspectiveCamera.position.z)<this.renderDistance()+pad;}
  destroy(){this.running=false;cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();this.renderer?.dispose?.();}
}
